/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.dip.authorize.role;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2016-12-05 22:12:30
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class RoleGroupVO extends SuperVO {
	private String pk_corp;
	private UFBoolean is_query;
	private String ts;
	private UFBoolean is_export;
	private UFBoolean is_cancal;
	private String group_memo;
	private UFBoolean is_delline;
	private UFBoolean is_save;
	private UFBoolean is_addline;
	private String group_code;
	private String group_name;
	private UFBoolean is_edit;
	private UFBoolean is_add;
	private Integer dr;
	private String pk_role_group;
	private UFBoolean is_import;
	private UFBoolean is_del;
	private UFBoolean is_extend;

	public static final String PK_CORP = "pk_corp";
	public static final String IS_QUERY = "is_query";
	public static final String IS_EXPORT = "is_export";
	public static final String IS_CANCAL = "is_cancal";
	public static final String GROUP_MEMO = "group_memo";
	public static final String IS_DELLINE = "is_delline";
	public static final String IS_SAVE = "is_save";
	public static final String IS_ADDLINE = "is_addline";
	public static final String GROUP_CODE = "group_code";
	public static final String GROUP_NAME = "group_name";
	public static final String IS_EDIT = "is_edit";
	public static final String IS_ADD = "is_add";
	public static final String PK_ROLE_GROUP = "pk_role_group";
	public static final String IS_IMPORT = "is_import";
	public static final String IS_DEL = "is_del";
			
	public UFBoolean getIs_extend() {
		return is_extend;
	}
	public void setIs_extend(UFBoolean is_extend) {
		this.is_extend = is_extend;
	}
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性is_query的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_query () {
		return is_query;
	}   
	/**
	 * 属性is_query的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_query UFBoolean
	 */
	public void setIs_query (UFBoolean newIs_query ) {
	 	this.is_query = newIs_query;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFDateTime
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newTs UFDateTime
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性is_export的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_export () {
		return is_export;
	}   
	/**
	 * 属性is_export的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_export UFBoolean
	 */
	public void setIs_export (UFBoolean newIs_export ) {
	 	this.is_export = newIs_export;
	} 	  
	/**
	 * 属性is_cancal的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_cancal () {
		return is_cancal;
	}   
	/**
	 * 属性is_cancal的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_cancal UFBoolean
	 */
	public void setIs_cancal (UFBoolean newIs_cancal ) {
	 	this.is_cancal = newIs_cancal;
	} 	  
	/**
	 * 属性group_memo的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return String
	 */
	public String getGroup_memo () {
		return group_memo;
	}   
	/**
	 * 属性group_memo的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newGroup_memo String
	 */
	public void setGroup_memo (String newGroup_memo ) {
	 	this.group_memo = newGroup_memo;
	} 	  
	/**
	 * 属性is_delline的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_delline () {
		return is_delline;
	}   
	/**
	 * 属性is_delline的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_delline UFBoolean
	 */
	public void setIs_delline (UFBoolean newIs_delline ) {
	 	this.is_delline = newIs_delline;
	} 	  
	/**
	 * 属性is_save的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_save () {
		return is_save;
	}   
	/**
	 * 属性is_save的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_save UFBoolean
	 */
	public void setIs_save (UFBoolean newIs_save ) {
	 	this.is_save = newIs_save;
	} 	  
	/**
	 * 属性is_addline的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_addline () {
		return is_addline;
	}   
	/**
	 * 属性is_addline的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_addline UFBoolean
	 */
	public void setIs_addline (UFBoolean newIs_addline ) {
	 	this.is_addline = newIs_addline;
	} 	  
	/**
	 * 属性group_code的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return String
	 */
	public String getGroup_code () {
		return group_code;
	}   
	/**
	 * 属性group_code的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newGroup_code String
	 */
	public void setGroup_code (String newGroup_code ) {
	 	this.group_code = newGroup_code;
	} 	  
	/**
	 * 属性group_name的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return String
	 */
	public String getGroup_name () {
		return group_name;
	}   
	/**
	 * 属性group_name的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newGroup_name String
	 */
	public void setGroup_name (String newGroup_name ) {
	 	this.group_name = newGroup_name;
	} 	  
	/**
	 * 属性is_edit的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_edit () {
		return is_edit;
	}   
	/**
	 * 属性is_edit的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_edit UFBoolean
	 */
	public void setIs_edit (UFBoolean newIs_edit ) {
	 	this.is_edit = newIs_edit;
	} 	  
	/**
	 * 属性is_add的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_add () {
		return is_add;
	}   
	/**
	 * 属性is_add的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_add UFBoolean
	 */
	public void setIs_add (UFBoolean newIs_add ) {
	 	this.is_add = newIs_add;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性pk_role_group的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return String
	 */
	public String getPk_role_group () {
		return pk_role_group;
	}   
	/**
	 * 属性pk_role_group的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newPk_role_group String
	 */
	public void setPk_role_group (String newPk_role_group ) {
	 	this.pk_role_group = newPk_role_group;
	} 	  
	/**
	 * 属性is_import的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_import () {
		return is_import;
	}   
	/**
	 * 属性is_import的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_import UFBoolean
	 */
	public void setIs_import (UFBoolean newIs_import ) {
	 	this.is_import = newIs_import;
	} 	  
	/**
	 * 属性is_del的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFBoolean
	 */
	public UFBoolean getIs_del () {
		return is_del;
	}   
	/**
	 * 属性is_del的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newIs_del UFBoolean
	 */
	public void setIs_del (UFBoolean newIs_del ) {
	 	this.is_del = newIs_del;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2016-12-05 22:12:30
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2016-12-05 22:12:30
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_role_group";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2016-12-05 22:12:30
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "dip_rolegroup";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2016-12-05 22:12:30
	  */
     public RoleGroupVO() {
		super();	
	}    
} 
