  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.credence;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-4-12
 * @author author
 * @version Your Project 1.0
 */
     public class CredenceBVO extends SuperVO {
           
             public String vdef4;
             public String verificationno;
             public String affect6;
             public String currency;
             public Integer dr;
             public String busdate;
             public String vdef2;
             public String numbers;
             public String affect5;
             public String ts;
             public String affect2;
             public String vdef1;
             public String subjects;
             public String pk_credence_h;
             public String affect7;
             public String affect3;
             public String summary;
             public String money;
             public String vdef3;
             public String affect4;
             public String remark;
             public String xtno;
             public String assistant;
             public String affect;
             public String direction;
             public String affect8;
             public String vdef5;
             public String pk_credence_b;
             public String ctrl;
            
             public static final String CTRL="ctrl";
             public static final String  VDEF4="vdef4";   
             public static final String  VERIFICATIONNO="verificationno";   
             public static final String  AFFECT6="affect6";   
             public static final String  CURRENCY="currency";   
             public static final String  DR="dr";   
             public static final String  BUSDATE="busdate";   
             public static final String  VDEF2="vdef2";   
             public static final String  NUMBERS="numbers";   
             public static final String  AFFECT5="affect5";   
             public static final String  TS="ts";   
             public static final String  AFFECT2="affect2";   
             public static final String  VDEF1="vdef1";   
             public static final String  SUBJECTS="subjects";   
             public static final String  PK_CREDENCE_H="pk_credence_h";   
             public static final String  AFFECT7="affect7";   
             public static final String  AFFECT3="affect3";   
             public static final String  SUMMARY="summary";   
             public static final String  MONEY="money";   
             public static final String  VDEF3="vdef3";   
             public static final String  AFFECT4="affect4";   
             public static final String  REMARK="remark";   
             public static final String  XTNO="xtno";   
             public static final String  ASSISTANT="assistant";   
             public static final String  AFFECT="affect";   
             public static final String  DIRECTION="direction";   
             public static final String  AFFECT8="affect8";   
             public static final String  VDEF5="vdef5";   
             public static final String  PK_CREDENCE_B="pk_credence_b";   
      
    
        public String getBusdate() {
				return busdate;
			}

			public void setBusdate(String busdate) {
				this.busdate = busdate;
			}

			public String getMoney() {
				return money;
			}

			public void setMoney(String money) {
				this.money = money;
			}

			public String getNumbers() {
				return numbers;
			}

			public void setNumbers(String numbers) {
				this.numbers = numbers;
			}

		/**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性verificationno的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getVerificationno() {
		 return verificationno;
	  }   
	  
     /**
	   * 属性verificationno的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newVerificationno String
	   */
	public void setVerificationno(String newVerificationno) {
		
		verificationno = newVerificationno;
	 } 	  
       
        /**
	   * 属性affect6的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getAffect6() {
		 return affect6;
	  }   
	  
     /**
	   * 属性affect6的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newAffect6 String
	   */
	public void setAffect6(String newAffect6) {
		
		affect6 = newAffect6;
	 } 	  
       
        /**
	   * 属性currency的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getCurrency() {
		 return currency;
	  }   
	  
     /**
	   * 属性currency的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newCurrency String
	   */
	public void setCurrency(String newCurrency) {
		
		currency = newCurrency;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性affect5的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getAffect5() {
		 return affect5;
	  }   
	  
     /**
	   * 属性affect5的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newAffect5 String
	   */
	public void setAffect5(String newAffect5) {
		
		affect5 = newAffect5;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}    
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性affect2的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getAffect2() {
		 return affect2;
	  }   
	  
     /**
	   * 属性affect2的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newAffect2 String
	   */
	public void setAffect2(String newAffect2) {
		
		affect2 = newAffect2;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性subjects的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getSubjects() {
		 return subjects;
	  }   
	  
     /**
	   * 属性subjects的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newSubjects String
	   */
	public void setSubjects(String newSubjects) {
		
		subjects = newSubjects;
	 } 	  
       
        /**
	   * 属性pk_credence_h的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getPk_credence_h() {
		 return pk_credence_h;
	  }   
	  
     /**
	   * 属性pk_credence_h的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newPk_credence_h String
	   */
	public void setPk_credence_h(String newPk_credence_h) {
		
		pk_credence_h = newPk_credence_h;
	 } 	  
       
        /**
	   * 属性affect7的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getAffect7() {
		 return affect7;
	  }   
	  
     /**
	   * 属性affect7的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newAffect7 String
	   */
	public void setAffect7(String newAffect7) {
		
		affect7 = newAffect7;
	 } 	  
       
        /**
	   * 属性affect3的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getAffect3() {
		 return affect3;
	  }   
	  
     /**
	   * 属性affect3的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newAffect3 String
	   */
	public void setAffect3(String newAffect3) {
		
		affect3 = newAffect3;
	 } 	  
       
        /**
	   * 属性summary的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getSummary() {
		 return summary;
	  }   
	  
     /**
	   * 属性summary的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newSummary String
	   */
	public void setSummary(String newSummary) {
		
		summary = newSummary;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性affect4的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getAffect4() {
		 return affect4;
	  }   
	  
     /**
	   * 属性affect4的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newAffect4 String
	   */
	public void setAffect4(String newAffect4) {
		
		affect4 = newAffect4;
	 } 	  
       
        /**
	   * 属性remark的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getRemark() {
		 return remark;
	  }   
	  
     /**
	   * 属性remark的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newRemark String
	   */
	public void setRemark(String newRemark) {
		
		remark = newRemark;
	 } 	  
       
        /**
	   * 属性xtno的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getXtno() {
		 return xtno;
	  }   
	  
     /**
	   * 属性xtno的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newXtno String
	   */
	public void setXtno(String newXtno) {
		
		xtno = newXtno;
	 } 	  
       
        /**
	   * 属性assistant的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getAssistant() {
		 return assistant;
	  }   
	  
     /**
	   * 属性assistant的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newAssistant String
	   */
	public void setAssistant(String newAssistant) {
		
		assistant = newAssistant;
	 } 	  
       
        /**
	   * 属性affect的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getAffect() {
		 return affect;
	  }   
	  
     /**
	   * 属性affect的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newAffect String
	   */
	public void setAffect(String newAffect) {
		
		affect = newAffect;
	 } 	  
       
        /**
	   * 属性direction的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getDirection() {
		 return direction;
	  }   
	  
     /**
	   * 属性direction的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newDirection String
	   */
	public void setDirection(String newDirection) {
		
		direction = newDirection;
	 } 	  
       
        /**
	   * 属性affect8的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getAffect8() {
		 return affect8;
	  }   
	  
     /**
	   * 属性affect8的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newAffect8 String
	   */
	public void setAffect8(String newAffect8) {
		
		affect8 = newAffect8;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
        /**
	   * 属性pk_credence_b的Getter方法.
	   *
	   * 创建日期:2011-4-12
	   * @return String
	   */
	 public String getPk_credence_b() {
		 return pk_credence_b;
	  }   
	  
     /**
	   * 属性pk_credence_b的Setter方法.
	   *
	   * 创建日期:2011-4-12
	   * @param newPk_credence_b String
	   */
	public void setPk_credence_b(String newPk_credence_b) {
		
		pk_credence_b = newPk_credence_b;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-4-12
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_credence_b == null) {
			errFields.add(new String("pk_credence_b"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-4-12
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_credence_h";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-4-12
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_credence_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-4-12
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_credence_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-4-12
	  */
	public CredenceBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-4-12
	 * @param newPk_credence_b 主键值
	 */
	 public CredenceBVO(String newPk_credence_b) {
		
		// 为主键字段赋值:
		 pk_credence_b = newPk_credence_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-12
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_credence_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-12
	  * @param newPk_credence_b  String    
	  */
	 public void setPrimaryKey(String newPk_credence_b) {
				
				pk_credence_b = newPk_credence_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-4-12
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_credence_b"; 
				
	 }

	public String getCtrl() {
		return ctrl;
	}

	public void setCtrl(String ctrl) {
		this.ctrl = ctrl;
	} 
} 
