  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.warningset;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-5-14
 * @author author
 * @version Your Project 1.0
 */
     public class DipWarningsetBVO extends SuperVO {
           
             public String vdef2;
             public String pk_datadefinit_h;
             public String vdef4;
             public String ts;
             public String pk_statusregist;
             public String pk_warningset_b;
             public String vdef1;
             public Integer dr;
             public String vdef3;
             public String vdef5;
             public String pk_warningset;
             public String operation;
             public Integer orderno;
            
             public static final String  VDEF2="vdef2";   
             public static final String  PK_DATADEFINIT_H="pk_datadefinit_h";   
             public static final String  VDEF4="vdef4";   
             public static final String  TS="ts";   
             public static final String  PK_STATUSREGIST="pk_statusregist";   
             public static final String  PK_WARNINGSET_B="pk_warningset_b";   
             public static final String  VDEF1="vdef1";   
             public static final String  DR="dr";   
             public static final String  VDEF3="vdef3";   
             public static final String  VDEF5="vdef5";   
             public static final String  PK_WARNINGSET="pk_warningset";   
             public static final String  OPERATION="operation";   
      
    
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性pk_datadefinit_h的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getPk_datadefinit_h() {
		 return pk_datadefinit_h;
	  }   
	  
     /**
	   * 属性pk_datadefinit_h的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newPk_datadefinit_h String
	   */
	public void setPk_datadefinit_h(String newPk_datadefinit_h) {
		
		pk_datadefinit_h = newPk_datadefinit_h;
	 } 	  
       
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}  
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性pk_statusregist的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getPk_statusregist() {
		 return pk_statusregist;
	  }   
	  
     /**
	   * 属性pk_statusregist的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newPk_statusregist String
	   */
	public void setPk_statusregist(String newPk_statusregist) {
		
		pk_statusregist = newPk_statusregist;
	 } 	  
       
        /**
	   * 属性pk_warningset_b的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getPk_warningset_b() {
		 return pk_warningset_b;
	  }   
	  
     /**
	   * 属性pk_warningset_b的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newPk_warningset_b String
	   */
	public void setPk_warningset_b(String newPk_warningset_b) {
		
		pk_warningset_b = newPk_warningset_b;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
        /**
	   * 属性pk_warningset的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getPk_warningset() {
		 return pk_warningset;
	  }   
	  
     /**
	   * 属性pk_warningset的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newPk_warningset String
	   */
	public void setPk_warningset(String newPk_warningset) {
		
		pk_warningset = newPk_warningset;
	 } 	  
       
        /**
	   * 属性operation的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getOperation() {
		 return operation;
	  }   
	  
     /**
	   * 属性operation的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newOperation String
	   */
	public void setOperation(String newOperation) {
		
		operation = newOperation;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-5-14
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_warningset_b == null) {
			errFields.add(new String("pk_warningset_b"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-5-14
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_warningset";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-5-14
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_warningset_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-5-14
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_warningset_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-5-14
	  */
	public DipWarningsetBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-5-14
	 * @param newPk_warningset_b 主键值
	 */
	 public DipWarningsetBVO(String newPk_warningset_b) {
		
		// 为主键字段赋值:
		 pk_warningset_b = newPk_warningset_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-14
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_warningset_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-14
	  * @param newPk_warningset_b  String    
	  */
	 public void setPrimaryKey(String newPk_warningset_b) {
				
				pk_warningset_b = newPk_warningset_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-5-14
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_warningset_b"; 
				
	 }

	public Integer getOrderno() {
		return orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	} 
} 
