  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.contdatawh;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-5-9
 * @author author
 * @version Your Project 1.0
 */
     public class ContdatawhBVO extends SuperVO {
           
             public Object vdef14;
             public Object vdef11;
             public Object vdef4;
             public String pk_contdatawh_h;
             public Object vdef7;
             public Integer dr;
             public Object vdef13;
             public Object vdef3;
             public String ncname;
             public Object vdef9;
             public Object vdef12;
             public Object vdef8;
             public Object vdef2;
             public String pk_contdatawh_b;
             public String ncbm;
             public String ts;
             public Object vdef6;
             public Object vdef15;
             public Object vdef10;
             public Object vdef1;
             public Object vdef5;
             public Object nccode;
             public UFBoolean isselect;
             
             public Object vdef16;
             public Object vdef17;
             public Object vdef18;
             public Object vdef19;
             public Object vdef20;
             public Object vdef21;
             public Object vdef22;
             public Object vdef23;
             public Object vdef24;
             public Object vdef25;
             public Object vdef26;
             public Object vdef27;
             public Object vdef28;
             public Object vdef29;
             public Object vdef30;
             public Object vdef31;
             public Object vdef32;
             public Object vdef33;
             public Object vdef34;
             public Object vdef35;
             public Object vdef36;
             public Object vdef37;
             public Object vdef38;
             public Object vdef39;
             public Object vdef40;
             public Object vdef41;
             public Object vdef42;
             public Object vdef43;
             public Object vdef44;
             public Object vdef45;
             public Object vdef46;
             public Object vdef47;
             public Object vdef48;
             public Object vdef49;
             public Object vdef50;
             public Object vdef51;
             public Object vdef52;
             public Object vdef53;
             public Object vdef54;
             public Object vdef55;
             public Object vdef56;
             public Object vdef57;
             public Object vdef58;
             public Object vdef59;
             public Object vdef60;
            
             public static final Object  VDEF4="vdef4";   
             public static final Object  VDEF18="vdef18";   
             public static final Object  PK_CONTDATAWH_H="pk_contdatawh_h";   
             public static final Object  DR="dr";   
             public static final Object  VDEF42="vdef42";   
             public static final Object  VDEF16="vdef16";   
             public static final Object  VDEF17="vdef17";   
             public static final Object  VDEF27="vdef27";   
             public static final Object  VDEF12="vdef12";   
             public static final Object  VDEF38="vdef38";   
             public static final Object  VDEF35="vdef35";   
             public static final Object  VDEF24="vdef24";   
             public static final Object  TS="ts";   
             public static final Object  VDEF25="vdef25";   
             public static final Object  VDEF60="vdef60";   
             public static final Object  VDEF19="vdef19";   
             public static final Object  VDEF48="vdef48";   
             public static final Object  VDEF51="vdef51";   
             public static final Object  VDEF13="vdef13";   
             public static final Object  VDEF3="vdef3";   
             public static final Object  VDEF53="vdef53";   
             public static final Object  NCNAME="ncname";   
             public static final Object  VDEF31="vdef31";   
             public static final Object  VDEF50="vdef50";   
             public static final Object  VDEF28="vdef28";   
             public static final Object  NCBM="ncbm";   
             public static final Object  VDEF23="vdef23";   
             public static final Object  PK_CONTDATAWH_B="pk_contdatawh_b";   
             public static final Object  VDEF52="vdef52";   
             public static final Object  VDEF44="vdef44";   
             public static final Object  VDEF29="vdef29";   
             public static final Object  VDEF10="vdef10";   
             public static final Object  NCCODE="nccode";   
             public static final Object  VDEF5="vdef5";   
             public static final Object  VDEF33="vdef33";   
             public static final Object  VDEF37="vdef37";   
             public static final Object  VDEF11="vdef11";   
             public static final Object  VDEF59="vdef59";   
             public static final Object  VDEF7="vdef7";   
             public static final Object  VDEF40="vdef40";   
             public static final Object  VDEF20="vdef20";   
             public static final Object  VDEF2="vdef2";   
             public static final Object  VDEF56="vdef56";   
             public static final Object  VDEF46="vdef46";   
             public static final Object  VDEF41="vdef41";   
             public static final Object  VDEF57="vdef57";   
             public static final Object  VDEF34="vdef34";   
             public static final Object  VDEF1="vdef1";   
             public static final Object  VDEF47="vdef47";   
             public static final Object  VDEF26="vdef26";   
             public static final Object  VDEF14="vdef14";   
             public static final Object  VDEF43="vdef43";   
             public static final Object  VDEF21="vdef21";   
             public static final Object  VDEF32="vdef32";   
             public static final Object  VDEF54="vdef54";   
             public static final Object  VDEF9="vdef9";   
             public static final Object  VDEF8="vdef8";   
             public static final Object  VDEF49="vdef49";   
             public static final Object  VDEF39="vdef39";   
             public static final Object  VDEF45="vdef45";   
             public static final Object  VDEF30="vdef30";   
             public static final Object  VDEF6="vdef6";   
             public static final Object  VDEF15="vdef15";   
             public static final Object  VDEF36="vdef36";   
             public static final Object  VDEF22="vdef22";   
             public static final Object  VDEF55="vdef55";   
             public static final Object  VDEF58="vdef58";   
      
    
        /**
	   * 属性vdef14的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef14() {
		 return vdef14;
	  }   
	  
     /**
	   * 属性vdef14的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef14 Object
	   */
	public void setVdef14(Object newVdef14) {
		
		vdef14 = newVdef14;
	 } 	  
       
        /**
	   * 属性vdef11的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef11() {
		 return vdef11;
	  }   
	  
     /**
	   * 属性vdef11的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef11 Object
	   */
	public void setVdef11(Object newVdef11) {
		
		vdef11 = newVdef11;
	 } 	  
       
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef4 Object
	   */
	public void setVdef4(Object newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性pk_contdatawh_h的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getPk_contdatawh_h() {
		 return pk_contdatawh_h;
	  }   
	  
     /**
	   * 属性pk_contdatawh_h的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newPk_contdatawh_h Object
	   */
	public void setPk_contdatawh_h(String newPk_contdatawh_h) {
		
		pk_contdatawh_h = newPk_contdatawh_h;
	 } 	  
       
        /**
	   * 属性vdef7的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef7() {
		 return vdef7;
	  }   
	  
     /**
	   * 属性vdef7的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef7 Object
	   */
	public void setVdef7(Object newVdef7) {
		
		vdef7 = newVdef7;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性vdef13的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef13() {
		 return vdef13;
	  }   
	  
     /**
	   * 属性vdef13的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef13 Object
	   */
	public void setVdef13(Object newVdef13) {
		
		vdef13 = newVdef13;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef3 Object
	   */
	public void setVdef3(Object newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性ncname的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getNcname() {
		 return ncname;
	  }   
	  
     /**
	   * 属性ncname的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newNcname Object
	   */
	public void setNcname(String newNcname) {
		
		ncname = newNcname;
	 } 	  
       
        /**
	   * 属性vdef9的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef9() {
		 return vdef9;
	  }   
	  
     /**
	   * 属性vdef9的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef9 Object
	   */
	public void setVdef9(Object newVdef9) {
		
		vdef9 = newVdef9;
	 } 	  
       
        /**
	   * 属性vdef12的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef12() {
		 return vdef12;
	  }   
	  
     /**
	   * 属性vdef12的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef12 Object
	   */
	public void setVdef12(Object newVdef12) {
		
		vdef12 = newVdef12;
	 } 	  
       
        /**
	   * 属性vdef8的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef8() {
		 return vdef8;
	  }   
	  
     /**
	   * 属性vdef8的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef8 Object
	   */
	public void setVdef8(Object newVdef8) {
		
		vdef8 = newVdef8;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef2 Object
	   */
	public void setVdef2(Object newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性pk_contdatawh_b的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getPk_contdatawh_b() {
		 return pk_contdatawh_b;
	  }   
	  
     /**
	   * 属性pk_contdatawh_b的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newPk_contdatawh_b Object
	   */
	public void setPk_contdatawh_b(String newPk_contdatawh_b) {
		
		pk_contdatawh_b = newPk_contdatawh_b;
	 } 	  
       
        /**
	   * 属性ncsyspk的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getNcbm() {
		 return ncbm;
	  }   
	  
     /**
	   * 属性ncsyspk的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newNcsyspk Object
	   */
	public void setNcbm(String newNcbm) {
		
		ncbm = newNcbm;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}  
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性vdef6的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef6() {
		 return vdef6;
	  }   
	  
     /**
	   * 属性vdef6的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef6 Object
	   */
	public void setVdef6(Object newVdef6) {
		
		vdef6 = newVdef6;
	 } 	  
       
        /**
	   * 属性vdef15的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef15() {
		 return vdef15;
	  }   
	  
     /**
	   * 属性vdef15的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef15 Object
	   */
	public void setVdef15(Object newVdef15) {
		
		vdef15 = newVdef15;
	 } 	  
       
        /**
	   * 属性vdef10的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef10() {
		 return vdef10;
	  }   
	  
     /**
	   * 属性vdef10的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef10 Object
	   */
	public void setVdef10(Object newVdef10) {
		
		vdef10 = newVdef10;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef1 Object
	   */
	public void setVdef1(Object newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef5 Object
	   */
	public void setVdef5(Object newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
        /**
	   * 属性ncsyscode的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Object
	   */
	 public Object getNccode() {
		 return nccode;
	  }   
	  
     /**
	   * 属性ncsyscode的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newNcsyscode Object
	   */
	public void setNccode(Object newNccode) {
		
		nccode = newNccode;
	 } 	  
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-5-9
	  * @return java.lang.Object
	  */
	public String getParentPKFieldName() {
	  	 
	 		return "pk_contdatawh_h";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-5-9
	  * @return java.lang.Object
	  */
	public String getPKFieldName() {
	 	  return "pk_contdatawh_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-5-9
	  * @return java.lang.Object
	 */
	public String getTableName() {
				
		return "dip_contdatawh_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-5-9
	  */
	public ContdatawhBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-5-9
	 * @param newPk_contdatawh_b 主键值
	 */
	 public ContdatawhBVO(String newPk_contdatawh_b) {
		
		// 为主键字段赋值:
		 pk_contdatawh_b = newPk_contdatawh_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-9
	  * @return Object
	  */
	   public String getPrimaryKey() {
				
		 return pk_contdatawh_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-9
	  * @param newPk_contdatawh_b  Object    
	  */
	 public void setPrimaryKey(String newPk_contdatawh_b) {
				
				pk_contdatawh_b = newPk_contdatawh_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-5-9
	   * @return java.lang.Object 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_contdatawh_b"; 
				
	 }

	public Object getVdef16() {
		return vdef16;
	}

	public void setVdef16(Object vdef16) {
		this.vdef16 = vdef16;
	}

	public Object getVdef17() {
		return vdef17;
	}

	public void setVdef17(Object vdef17) {
		this.vdef17 = vdef17;
	}

	public Object getVdef18() {
		return vdef18;
	}

	public void setVdef18(Object vdef18) {
		this.vdef18 = vdef18;
	}

	public Object getVdef19() {
		return vdef19;
	}

	public void setVdef19(Object vdef19) {
		this.vdef19 = vdef19;
	}

	public Object getVdef20() {
		return vdef20;
	}

	public void setVdef20(Object vdef20) {
		this.vdef20 = vdef20;
	}

	public Object getVdef21() {
		return vdef21;
	}

	public void setVdef21(Object vdef21) {
		this.vdef21 = vdef21;
	}

	public Object getVdef22() {
		return vdef22;
	}

	public void setVdef22(Object vdef22) {
		this.vdef22 = vdef22;
	}

	public Object getVdef23() {
		return vdef23;
	}

	public void setVdef23(Object vdef23) {
		this.vdef23 = vdef23;
	}

	public Object getVdef24() {
		return vdef24;
	}

	public void setVdef24(Object vdef24) {
		this.vdef24 = vdef24;
	}

	public Object getVdef25() {
		return vdef25;
	}

	public void setVdef25(Object vdef25) {
		this.vdef25 = vdef25;
	}

	public Object getVdef26() {
		return vdef26;
	}

	public void setVdef26(Object vdef26) {
		this.vdef26 = vdef26;
	}

	public Object getVdef27() {
		return vdef27;
	}

	public void setVdef27(Object vdef27) {
		this.vdef27 = vdef27;
	}

	public Object getVdef28() {
		return vdef28;
	}

	public void setVdef28(Object vdef28) {
		this.vdef28 = vdef28;
	}

	public Object getVdef29() {
		return vdef29;
	}

	public void setVdef29(Object vdef29) {
		this.vdef29 = vdef29;
	}

	public Object getVdef30() {
		return vdef30;
	}

	public void setVdef30(Object vdef30) {
		this.vdef30 = vdef30;
	}

	public Object getVdef31() {
		return vdef31;
	}

	public void setVdef31(Object vdef31) {
		this.vdef31 = vdef31;
	}

	public Object getVdef32() {
		return vdef32;
	}

	public void setVdef32(Object vdef32) {
		this.vdef32 = vdef32;
	}

	public Object getVdef33() {
		return vdef33;
	}

	public void setVdef33(Object vdef33) {
		this.vdef33 = vdef33;
	}

	public Object getVdef34() {
		return vdef34;
	}

	public void setVdef34(Object vdef34) {
		this.vdef34 = vdef34;
	}

	public Object getVdef35() {
		return vdef35;
	}

	public void setVdef35(Object vdef35) {
		this.vdef35 = vdef35;
	}

	public Object getVdef36() {
		return vdef36;
	}

	public void setVdef36(Object vdef36) {
		this.vdef36 = vdef36;
	}

	public Object getVdef37() {
		return vdef37;
	}

	public void setVdef37(Object vdef37) {
		this.vdef37 = vdef37;
	}

	public Object getVdef38() {
		return vdef38;
	}

	public void setVdef38(Object vdef38) {
		this.vdef38 = vdef38;
	}

	public Object getVdef39() {
		return vdef39;
	}

	public void setVdef39(Object vdef39) {
		this.vdef39 = vdef39;
	}

	public Object getVdef40() {
		return vdef40;
	}

	public void setVdef40(Object vdef40) {
		this.vdef40 = vdef40;
	}

	public Object getVdef41() {
		return vdef41;
	}

	public void setVdef41(Object vdef41) {
		this.vdef41 = vdef41;
	}

	public Object getVdef42() {
		return vdef42;
	}

	public void setVdef42(Object vdef42) {
		this.vdef42 = vdef42;
	}

	public Object getVdef43() {
		return vdef43;
	}

	public void setVdef43(Object vdef43) {
		this.vdef43 = vdef43;
	}

	public Object getVdef44() {
		return vdef44;
	}

	public void setVdef44(Object vdef44) {
		this.vdef44 = vdef44;
	}

	public Object getVdef45() {
		return vdef45;
	}

	public void setVdef45(Object vdef45) {
		this.vdef45 = vdef45;
	}

	public Object getVdef46() {
		return vdef46;
	}

	public void setVdef46(Object vdef46) {
		this.vdef46 = vdef46;
	}

	public Object getVdef47() {
		return vdef47;
	}

	public void setVdef47(Object vdef47) {
		this.vdef47 = vdef47;
	}

	public Object getVdef48() {
		return vdef48;
	}

	public void setVdef48(Object vdef48) {
		this.vdef48 = vdef48;
	}

	public Object getVdef49() {
		return vdef49;
	}

	public void setVdef49(Object vdef49) {
		this.vdef49 = vdef49;
	}

	public Object getVdef50() {
		return vdef50;
	}

	public void setVdef50(Object vdef50) {
		this.vdef50 = vdef50;
	}

	public Object getVdef51() {
		return vdef51;
	}

	public void setVdef51(Object vdef51) {
		this.vdef51 = vdef51;
	}

	public Object getVdef52() {
		return vdef52;
	}

	public void setVdef52(Object vdef52) {
		this.vdef52 = vdef52;
	}

	public Object getVdef53() {
		return vdef53;
	}

	public void setVdef53(Object vdef53) {
		this.vdef53 = vdef53;
	}

	public Object getVdef54() {
		return vdef54;
	}

	public void setVdef54(Object vdef54) {
		this.vdef54 = vdef54;
	}

	public Object getVdef55() {
		return vdef55;
	}

	public void setVdef55(Object vdef55) {
		this.vdef55 = vdef55;
	}

	public Object getVdef56() {
		return vdef56;
	}

	public void setVdef56(Object vdef56) {
		this.vdef56 = vdef56;
	}

	public Object getVdef57() {
		return vdef57;
	}

	public void setVdef57(Object vdef57) {
		this.vdef57 = vdef57;
	}

	public Object getVdef58() {
		return vdef58;
	}

	public void setVdef58(Object vdef58) {
		this.vdef58 = vdef58;
	}

	public Object getVdef59() {
		return vdef59;
	}

	public void setVdef59(Object vdef59) {
		this.vdef59 = vdef59;
	}

	public Object getVdef60() {
		return vdef60;
	}

	public void setVdef60(Object vdef60) {
		this.vdef60 = vdef60;
	}

	public UFBoolean getIsselect() {
		return isselect;
	}

	public void setIsselect(UFBoolean isselect) {
		this.isselect = isselect;
	} 
} 
