/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.dip.authorize.role;
	
import nc.vo.pub.SuperVO;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2016-12-05 22:12:30
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class RoleGroupBVO extends SuperVO {
	private String pk_corp;
	private String ts;
	private String pk_role_group_b;
	private Integer dr;
	private String pk_role_group;
	private String pk_role;

	public static final String PK_CORP = "pk_corp";
	public static final String PK_ROLE_GROUP_B = "pk_role_group_b";
	public static final String GROUP_NAME = "group_name";
	public static final String GROUP_MEMO = "group_memo";
	public static final String GROUP_CODE = "group_code";
	public static final String PK_ROLE_GROUP = "pk_role_group";
	public static final String PK_ROLE = "pk_role";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFDateTime
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newTs UFDateTime
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性pk_role_group_b的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return String
	 */
	public String getPk_role_group_b () {
		return pk_role_group_b;
	}   
	/**
	 * 属性pk_role_group_b的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newPk_role_group_b String
	 */
	public void setPk_role_group_b (String newPk_role_group_b ) {
	 	this.pk_role_group_b = newPk_role_group_b;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性pk_role_group的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return String
	 */
	public String getPk_role_group () {
		return pk_role_group;
	}   
	/**
	 * 属性pk_role_group的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newPk_role_group String
	 */
	public void setPk_role_group (String newPk_role_group ) {
	 	this.pk_role_group = newPk_role_group;
	} 	  
	/**
	 * 属性pk_role的Getter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @return String
	 */
	public String getPk_role () {
		return pk_role;
	}   
	/**
	 * 属性pk_role的Setter方法.
	 * 创建日期:2016-12-05 22:12:30
	 * @param newPk_role String
	 */
	public void setPk_role (String newPk_role ) {
	 	this.pk_role = newPk_role;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2016-12-05 22:12:30
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "PK_ROLE_GROUP";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2016-12-05 22:12:30
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_role_group_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2016-12-05 22:12:30
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "dip_rolegroup_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2016-12-05 22:12:30
	  */
     public RoleGroupBVO() {
		super();	
	}    
} 
