  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.warningset;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-5-14
 * @author author
 * @version Your Project 1.0
 */
     public class DipWarningsetVO extends SuperVO {
           
             public String wartime;
             public String vdef4;
             public String pk_sys;
             public String pk_taskregister;
             public String isnotwarning;
             public Integer dr;
             public String pk_warningset;
             public String runservice;
             public String condition;
             public String vdef2;
             public String stabname;
             public String wname;
             public String ts;
             public String vdef1;
             public String tabdate;
             public String thistime;
             public String wcode;
             public String property;
             public String pk_bustab;
             public String vdef3;
             public String tabstatus;
             public String isnottiming;
             public String nexttime;
             public String propty;
             public String vdef5;
             public String tasktype;
            
             public static final String  WARTIME="wartime";   
             public static final String  VDEF4="vdef4";   
             public static final String  PK_SYS="pk_sys";   
             public static final String  PK_TASKREGISTER="pk_taskregister";   
             public static final String  ISNOTWARNING="isnotwarning";   
             public static final String  DR="dr";   
             public static final String  PK_WARNINGSET="pk_warningset";   
             public static final String  RUNSERVICE="runservice";   
             public static final String  CONDITION="condition";   
             public static final String  VDEF2="vdef2";   
             public static final String  STABNAME="stabname";   
             public static final String  WNAME="wname";   
             public static final String  TS="ts";   
             public static final String  VDEF1="vdef1";   
             public static final String  TABDATE="tabdate";   
             public static final String  THISTIME="thistime";   
             public static final String  WCODE="wcode";   
             public static final String  PROPERTY="property";   
             public static final String  PK_BUSTAB="pk_bustab";   
             public static final String  VDEF3="vdef3";   
             public static final String  TABSTATUS="tabstatus";   
             public static final String  ISNOTTIMING="isnottiming";   
             public static final String  NEXTTIME="nexttime";   
             public static final String  PROPTY="propty";   
             public static final String  VDEF5="vdef5";   
             public static final String  TASKTYPE="tasktype";   
      
    
        /**
	   * 属性wartime的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getWartime() {
		 return wartime;
	  }   
	  
     /**
	   * 属性wartime的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newWartime String
	   */
	public void setWartime(String newWartime) {
		
		wartime = newWartime;
	 } 	  
       
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性pk_sys的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getPk_sys() {
		 return pk_sys;
	  }   
	  
     /**
	   * 属性pk_sys的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newPk_sys String
	   */
	public void setPk_sys(String newPk_sys) {
		
		pk_sys = newPk_sys;
	 } 	  
       
        /**
	   * 属性pk_taskregister的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getPk_taskregister() {
		 return pk_taskregister;
	  }   
	  
     /**
	   * 属性pk_taskregister的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newPk_taskregister String
	   */
	public void setPk_taskregister(String newPk_taskregister) {
		
		pk_taskregister = newPk_taskregister;
	 } 	  
       
        /**
	   * 属性isnotwarning的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getIsnotwarning() {
		 return isnotwarning;
	  }   
	  
     /**
	   * 属性isnotwarning的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newIsnotwarning String
	   */
	public void setIsnotwarning(String newIsnotwarning) {
		
		isnotwarning = newIsnotwarning;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性pk_warningset的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getPk_warningset() {
		 return pk_warningset;
	  }   
	  
     /**
	   * 属性pk_warningset的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newPk_warningset String
	   */
	public void setPk_warningset(String newPk_warningset) {
		
		pk_warningset = newPk_warningset;
	 } 	  
       
        /**
	   * 属性runservice的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getRunservice() {
		 return runservice;
	  }   
	  
     /**
	   * 属性runservice的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newRunservice String
	   */
	public void setRunservice(String newRunservice) {
		
		runservice = newRunservice;
	 } 	  
       
        /**
	   * 属性condition的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getCondition() {
		 return condition;
	  }   
	  
     /**
	   * 属性condition的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newCondition String
	   */
	public void setCondition(String newCondition) {
		
		condition = newCondition;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性stabname的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getStabname() {
		 return stabname;
	  }   
	  
     /**
	   * 属性stabname的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newStabname String
	   */
	public void setStabname(String newStabname) {
		
		stabname = newStabname;
	 } 	  
       
        /**
	   * 属性wname的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getWname() {
		 return wname;
	  }   
	  
     /**
	   * 属性wname的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newWname String
	   */
	public void setWname(String newWname) {
		
		wname = newWname;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}    
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性tabdate的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getTabdate() {
		 return tabdate;
	  }   
	  
     /**
	   * 属性tabdate的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newTabdate String
	   */
	public void setTabdate(String newTabdate) {
		
		tabdate = newTabdate;
	 } 	  
       
        /**
	   * 属性thistime的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getThistime() {
		 return thistime;
	  }   
	  
     /**
	   * 属性thistime的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newThistime String
	   */
	public void setThistime(String newThistime) {
		
		thistime = newThistime;
	 } 	  
       
        /**
	   * 属性wcode的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getWcode() {
		 return wcode;
	  }   
	  
     /**
	   * 属性wcode的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newWcode String
	   */
	public void setWcode(String newWcode) {
		
		wcode = newWcode;
	 } 	  
       
        /**
	   * 属性property的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getProperty() {
		 return property;
	  }   
	  
     /**
	   * 属性property的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newProperty String
	   */
	public void setProperty(String newProperty) {
		
		property = newProperty;
	 } 	  
       
        /**
	   * 属性pk_bustab的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getPk_bustab() {
		 return pk_bustab;
	  }   
	  
     /**
	   * 属性pk_bustab的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newPk_bustab String
	   */
	public void setPk_bustab(String newPk_bustab) {
		
		pk_bustab = newPk_bustab;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性tabstatus的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getTabstatus() {
		 return tabstatus;
	  }   
	  
     /**
	   * 属性tabstatus的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newTabstatus String
	   */
	public void setTabstatus(String newTabstatus) {
		
		tabstatus = newTabstatus;
	 } 	  
       
        /**
	   * 属性isnottiming的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getIsnottiming() {
		 return isnottiming;
	  }   
	  
     /**
	   * 属性isnottiming的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newIsnottiming String
	   */
	public void setIsnottiming(String newIsnottiming) {
		
		isnottiming = newIsnottiming;
	 } 	  
       
        /**
	   * 属性nexttime的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getNexttime() {
		 return nexttime;
	  }   
	  
     /**
	   * 属性nexttime的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newNexttime String
	   */
	public void setNexttime(String newNexttime) {
		
		nexttime = newNexttime;
	 } 	  
       
        /**
	   * 属性propty的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getPropty() {
		 return propty;
	  }   
	  
     /**
	   * 属性propty的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newPropty String
	   */
	public void setPropty(String newPropty) {
		
		propty = newPropty;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
        /**
	   * 属性task的Getter方法.
	   *
	   * 创建日期:2011-5-14
	   * @return String
	   */
	 public String getTasktype() {
		 return tasktype;
	  }   
	  
     /**
	   * 属性task的Setter方法.
	   *
	   * 创建日期:2011-5-14
	   * @param newTask String
	   */
	public void setTasktype(String newTasktype) {
		
		tasktype = newTasktype;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-5-14
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_warningset == null) {
			errFields.add(new String("pk_warningset"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-5-14
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-5-14
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_warningset";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-5-14
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_warningset";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-5-14
	  */
	public DipWarningsetVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-5-14
	 * @param newPk_warningset 主键值
	 */
	 public DipWarningsetVO(String newPk_warningset) {
		
		// 为主键字段赋值:
		 pk_warningset = newPk_warningset;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-14
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_warningset;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-14
	  * @param newPk_warningset  String    
	  */
	 public void setPrimaryKey(String newPk_warningset) {
				
				pk_warningset = newPk_warningset; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-5-14
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_warningset"; 
				
	 } 
} 
