  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.tabstatus;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-5-12
 * @author author
 * @version Your Project 1.0
 */
     public class TabstatusBVO extends SuperVO {
           
             public String active;
             public Integer faildata;
             public String def_str_3;
             public Integer dr;
             public String mydate;
             public String oper;
             public String pk_tabstatus_h;
             public String ts;
             public String def_str_1;
             public String pk_tabstatus_b;
             public String state;
             public Integer def_integer;
             public Integer accessdata;
             public UFDouble def_double;
             public String def_str_2;
            
             public static final String  ACTIVE="active";   
             public static final String  FAILDATA="faildata";   
             public static final String  DEF_STR_3="def_str_3";   
             public static final String  DR="dr";   
             public static final String  MYDATE="mydate";   
             public static final String  OPER="oper";   
             public static final String  PK_TABSTATUS_H="pk_tabstatus_h";   
             public static final String  TS="ts";   
             public static final String  DEF_STR_1="def_str_1";   
             public static final String  PK_TABSTATUS_B="pk_tabstatus_b";   
             public static final String  STATE="state";   
             public static final String  DEF_INTEGER="def_integer";   
             public static final String  ACCESSDATA="accessdata";   
             public static final String  DEF_DOUBLE="def_double";   
             public static final String  DEF_STR_2="def_str_2";   
      
    
        /**
	   * 属性active的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return String
	   */
	 public String getActive() {
		 return active;
	  }   
	  
     /**
	   * 属性active的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newActive String
	   */
	public void setActive(String newActive) {
		
		active = newActive;
	 } 	  
       
        /**
	   * 属性faildata的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return Integer
	   */
	 public Integer getFaildata() {
		 return faildata;
	  }   
	  
     /**
	   * 属性faildata的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newFaildata Integer
	   */
	public void setFaildata(Integer newFaildata) {
		
		faildata = newFaildata;
	 } 	  
       
        /**
	   * 属性def_str_3的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return String
	   */
	 public String getDef_str_3() {
		 return def_str_3;
	  }   
	  
     /**
	   * 属性def_str_3的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newDef_str_3 String
	   */
	public void setDef_str_3(String newDef_str_3) {
		
		def_str_3 = newDef_str_3;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性mydate的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return String
	   */
	 public String getMydate() {
		 return mydate;
	  }   
	  
     /**
	   * 属性mydate的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newMydate String
	   */
	public void setMydate(String newMydate) {
		
		mydate = newMydate;
	 } 	  
       
        /**
	   * 属性oper的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return String
	   */
	 public String getOper() {
		 return oper;
	  }   
	  
     /**
	   * 属性oper的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newOper String
	   */
	public void setOper(String newOper) {
		
		oper = newOper;
	 } 	  
       
        /**
	   * 属性pk_tabstatus_h的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return String
	   */
	 public String getPk_tabstatus_h() {
		 return pk_tabstatus_h;
	  }   
	  
     /**
	   * 属性pk_tabstatus_h的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newPk_tabstatus_h String
	   */
	public void setPk_tabstatus_h(String newPk_tabstatus_h) {
		
		pk_tabstatus_h = newPk_tabstatus_h;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}  
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性def_str_1的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return String
	   */
	 public String getDef_str_1() {
		 return def_str_1;
	  }   
	  
     /**
	   * 属性def_str_1的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newDef_str_1 String
	   */
	public void setDef_str_1(String newDef_str_1) {
		
		def_str_1 = newDef_str_1;
	 } 	  
       
        /**
	   * 属性pk_tabstatus_b的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return String
	   */
	 public String getPk_tabstatus_b() {
		 return pk_tabstatus_b;
	  }   
	  
     /**
	   * 属性pk_tabstatus_b的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newPk_tabstatus_b String
	   */
	public void setPk_tabstatus_b(String newPk_tabstatus_b) {
		
		pk_tabstatus_b = newPk_tabstatus_b;
	 } 	  
       
        /**
	   * 属性state的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return String
	   */
	 public String getState() {
		 return state;
	  }   
	  
     /**
	   * 属性state的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newState String
	   */
	public void setState(String newState) {
		
		state = newState;
	 } 	  
       
        /**
	   * 属性def_integer的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return Integer
	   */
	 public Integer getDef_integer() {
		 return def_integer;
	  }   
	  
     /**
	   * 属性def_integer的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newDef_integer Integer
	   */
	public void setDef_integer(Integer newDef_integer) {
		
		def_integer = newDef_integer;
	 } 	  
       
        /**
	   * 属性accessdata的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return Integer
	   */
	 public Integer getAccessdata() {
		 return accessdata;
	  }   
	  
     /**
	   * 属性accessdata的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newAccessdata Integer
	   */
	public void setAccessdata(Integer newAccessdata) {
		
		accessdata = newAccessdata;
	 } 	  
       
        /**
	   * 属性def_double的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return UFDouble
	   */
	 public UFDouble getDef_double() {
		 return def_double;
	  }   
	  
     /**
	   * 属性def_double的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newDef_double UFDouble
	   */
	public void setDef_double(UFDouble newDef_double) {
		
		def_double = newDef_double;
	 } 	  
       
        /**
	   * 属性def_str_2的Getter方法.
	   *
	   * 创建日期:2011-5-12
	   * @return String
	   */
	 public String getDef_str_2() {
		 return def_str_2;
	  }   
	  
     /**
	   * 属性def_str_2的Setter方法.
	   *
	   * 创建日期:2011-5-12
	   * @param newDef_str_2 String
	   */
	public void setDef_str_2(String newDef_str_2) {
		
		def_str_2 = newDef_str_2;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-5-12
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_tabstatus_b == null) {
			errFields.add(new String("pk_tabstatus_b"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-5-12
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_tabstatus_h";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-5-12
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_tabstatus_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-5-12
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_tabstatus_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-5-12
	  */
	public TabstatusBVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-5-12
	 * @param newPk_tabstatus_b 主键值
	 */
	 public TabstatusBVO(String newPk_tabstatus_b) {
		
		// 为主键字段赋值:
		 pk_tabstatus_b = newPk_tabstatus_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-12
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_tabstatus_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-12
	  * @param newPk_tabstatus_b  String    
	  */
	 public void setPrimaryKey(String newPk_tabstatus_b) {
				
				pk_tabstatus_b = newPk_tabstatus_b; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-5-12
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_tabstatus_b"; 
				
	 } 
} 
