  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.dataformatdef;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
import nc.vo.pub.*;
import nc.vo.pub.lang.UFDateTime;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-4-17
 * @author author
 * @version Your Project 1.0
 */
     public class DataformatdefHVO extends SuperVO {
           
             public String vdef4;
             public String type;
             public String messflowtype;
             public Integer dr;
             public String vdef3;
             public String code;
             public String vdef2;
             public String pk_dataformatdef_h;
             public String ts;
             public String vdef1;
             public String vdef5;
             public String name;
             public String messflowdef;//对照方式，顺序（0）或者字段（1）
             public String pk_datarec_h;
             public String beginsign;//分割标记
             public String endsign;
             public Integer filetype;//文件类型，0 txt,1 xml,2 excel
             public Integer mergecount;
             public Integer pagerunsys;//合并类型，查询时候页查询时候，对每页设置的一个参数。
             public String mergemark;
             public String mergestyle;//合并类型  0表示正常模式，1表示记录合并，2表示完全合并
             public Integer delayed;//延时时间
             public String sendstyle;//发送类型 0 不发送，1发送
             
             public static final String  VDEF4="vdef4";   
             public static final String  TYPE="type";   
             public static final String  MESSFLOWTYPE="messflowtype";   
             public static final String  DR="dr";   
             public static final String  VDEF3="vdef3";   
             public static final String  CODE="code";   
             public static final String  VDEF2="vdef2";   
             public static final String  PK_DATAFORMATDEF_H="pk_dataformatdef_h";   
             public static final String  TS="ts";   
             public static final String  VDEF1="vdef1";   
             public static final String  VDEF5="vdef5";   
             public static final String  NAME="name";   
             public static final String  MESSFLOWDEF="messflowdef";  
             public static final String  PK_DATAREC_H="pk_datarec_h";
             public static final String  BEGINSIGN="beginsign";
             public static final String  ENDSIGN="endsign";
             public static final String  MERGERCOUNT="mergecount";
             public static final String  MERGEMARK="mergemark";
             public static final String  MERGESTYLE="mergestyle";
             public static final String  DELAYED="delayed";
             public static final String  SENDSTYLE="sendstyle";
             public static final String  PAGERUNSYS="pagerunsys";
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性type的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getType() {
		 return type;
	  }   
	  
     /**
	   * 属性type的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newType String
	   */
	public void setType(String newType) {
		
		type = newType;
	 } 	  
       
      
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性code的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getCode() {
		 return code;
	  }   
	  
     /**
	   * 属性code的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newCode String
	   */
	public void setCode(String newCode) {
		
		code = newCode;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性pk_dataformatdef_h的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getPk_dataformatdef_h() {
		 return pk_dataformatdef_h;
	  }   
	  
     /**
	   * 属性pk_dataformatdef_h的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newPk_dataformatdef_h String
	   */
	public void setPk_dataformatdef_h(String newPk_dataformatdef_h) {
		
		pk_dataformatdef_h = newPk_dataformatdef_h;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}    
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
        /**
	   * 属性name的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getName() {
		 return name;
	  }   
	  
     /**
	   * 属性name的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newName String
	   */
	public void setName(String newName) {
		
		name = newName;
	 } 	  
       
        /**
	   * 属性messflowdef的Getter方法.
	   *
	   * 创建日期:2011-4-17
	   * @return String
	   */
	 public String getMessflowdef() {
		 return messflowdef;
	  }   
	  
     /**
	   * 属性messflowdef的Setter方法.
	   *
	   * 创建日期:2011-4-17
	   * @param newMessflowdef String
	   */
	public void setMessflowdef(String newMessflowdef) {
		
		messflowdef = newMessflowdef;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-4-17
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_dataformatdef_h == null) {
			errFields.add(new String("pk_dataformatdef_h"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-4-17
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-4-17
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_dataformatdef_h";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-4-17
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_dataformatdef_h";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-4-17
	  */
	public DataformatdefHVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-4-17
	 * @param newPk_dataformatdef_h 主键值
	 */
	 public DataformatdefHVO(String newPk_dataformatdef_h) {
		
		// 为主键字段赋值:
		 pk_dataformatdef_h = newPk_dataformatdef_h;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-17
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_dataformatdef_h;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-17
	  * @param newPk_dataformatdef_h  String    
	  */
	 public void setPrimaryKey(String newPk_dataformatdef_h) {
				
				pk_dataformatdef_h = newPk_dataformatdef_h; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-4-17
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_dataformatdef_h"; 
				
	 }

	public String getMessflowtype() {
		return messflowtype;
	}

	public void setMessflowtype(String messflowtype) {
		this.messflowtype = messflowtype;
	}

	public String getPk_datarec_h() {
		return pk_datarec_h;
	}

	public void setPk_datarec_h(String pk_datarec_h) {
		this.pk_datarec_h = pk_datarec_h;
	}

	public String getBeginsign() {
		return beginsign;
	}

	public void setBeginsign(String beginsign) {
		this.beginsign = beginsign;
	}

	public String getEndsign() {
		return endsign;
	}

	public void setEndsign(String endsign) {
		this.endsign = endsign;
	}

	public Integer getFiletype() {
		return filetype;
	}

	public void setFiletype(Integer filetype) {
		this.filetype = filetype;
	} 

	public Integer getMergecount() {
		return mergecount;
	}

	public void setMergecount(Integer mergecount) {
		this.mergecount = mergecount;
	}

	public String getMergemark() {
		return mergemark;
	}

	public void setMergemark(String mergemark) {
		this.mergemark = mergemark;
	}

	public String getMergestyle() {
		return mergestyle;
	}

	public void setMergestyle(String mergestyle) {
		this.mergestyle = mergestyle;
	}

	public Integer getDelayed() {
		return delayed;
	}

	public void setDelayed(Integer delayed) {
		this.delayed = delayed;
	}

	public String getSendstyle() {
		return sendstyle;
	}

	public void setSendstyle(String sendstyle) {
		this.sendstyle = sendstyle;
	}

	public Integer getPagerunsys() {
		return pagerunsys;
	}

	public void setPagerunsys(Integer pagerunsys) {
		this.pagerunsys = pagerunsys;
	} 
	
	
	
} 
