  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.managerserver;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
import nc.vo.dip.messservtype.MessservtypeVO;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-4-2
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DipManagerserverVO extends SuperVO {
           
             public String mstatus;
             public String def_str_3;
             public Integer dr;
             public String pk_managerserver;
             public String mname;
             public String workcont;
             public String sysname;
             public String syscode;
             public String def_str_1;
             public String ts;
             public Integer def_integer;
             public UFDouble def_double;
             public String def_str_2;
             public String runservice;
             public String startandstorp;
             public boolean ismsg;//如果是消息类，就是true,否则是Fasle
             public MessservtypeVO mesvo;
             public String threadname;
            
             
             public static final String  MSTATUS="mstatus";   
             public static final String  STARTANDSTORP="startandstorp";   
             public static final String  DEF_STR_3="def_str_3";   
             public static final String  DR="dr";   
             public static final String  PK_MANAGERSERVER="pk_managerserver";   
             public static final String  MNAME="mname";   
             public static final String  WORKCONT="workcont";   
             public static final String  SYSNAME="sysname";   
             public static final String  SYSCODE="syscode";   
             public static final String  DEF_STR_1="def_str_1";   
             public static final String  TS="ts";   
             public static final String  DEF_INTEGER="def_integer";   
             public static final String  DEF_DOUBLE="def_double";   
             public static final String  DEF_STR_2="def_str_2";  
             public static final String RUNSERVICE="runservice";
             public static final String ISMSG="ismsg";
      
    
        public boolean isIsmsg() {
				return ismsg;
			}

			public void setIsmsg(boolean ismsg) {
				this.ismsg = ismsg;
			}

		public String getStartandstorp() {
				return startandstorp;
			}

			public void setStartandstorp(String startandstorp) {
				this.startandstorp = startandstorp;
			}

		public String getRunservice() {
				return runservice;
			}

			public void setRunservice(String runservice) {
				this.runservice = runservice;
			}

		/**
	   * 属性mstatus的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return String
	   */
	 public String getMstatus() {
		 return mstatus;
	  }   
	  
     /**
	   * 属性mstatus的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newMstatus String
	   */
	public void setMstatus(String newMstatus) {
		
		mstatus = newMstatus;
	 } 	  
       
        /**
	   * 属性def_str_3的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return String
	   */
	 public String getDef_str_3() {
		 return def_str_3;
	  }   
	  
     /**
	   * 属性def_str_3的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newDef_str_3 String
	   */
	public void setDef_str_3(String newDef_str_3) {
		
		def_str_3 = newDef_str_3;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性pk_managerserver的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return String
	   */
	 public String getPk_managerserver() {
		 return pk_managerserver;
	  }   
	  
     /**
	   * 属性pk_managerserver的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newPk_managerserver String
	   */
	public void setPk_managerserver(String newPk_managerserver) {
		
		pk_managerserver = newPk_managerserver;
	 } 	  
       
        /**
	   * 属性mname的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return String
	   */
	 public String getMname() {
		 return mname;
	  }   
	  
     /**
	   * 属性mname的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newMname String
	   */
	public void setMname(String newMname) {
		
		mname = newMname;
	 } 	  
       
        /**
	   * 属性workcont的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return String
	   */
	 public String getWorkcont() {
		 return workcont;
	  }   
	  
     /**
	   * 属性workcont的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newWorkcont String
	   */
	public void setWorkcont(String newWorkcont) {
		
		workcont = newWorkcont;
	 } 	  
       
        /**
	   * 属性sysname的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return String
	   */
	 public String getSysname() {
		 return sysname;
	  }   
	  
     /**
	   * 属性sysname的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newSysname String
	   */
	public void setSysname(String newSysname) {
		
		sysname = newSysname;
	 } 	  
       
        /**
	   * 属性syscode的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return String
	   */
	 public String getSyscode() {
		 return syscode;
	  }   
	  
     /**
	   * 属性syscode的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newSyscode String
	   */
	public void setSyscode(String newSyscode) {
		
		syscode = newSyscode;
	 } 	  
       
        /**
	   * 属性def_str_1的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return String
	   */
	 public String getDef_str_1() {
		 return def_str_1;
	  }   
	  
     /**
	   * 属性def_str_1的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newDef_str_1 String
	   */
	public void setDef_str_1(String newDef_str_1) {
		
		def_str_1 = newDef_str_1;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}    
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性def_integer的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return Integer
	   */
	 public Integer getDef_integer() {
		 return def_integer;
	  }   
	  
     /**
	   * 属性def_integer的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newDef_integer Integer
	   */
	public void setDef_integer(Integer newDef_integer) {
		
		def_integer = newDef_integer;
	 } 	  
       
        /**
	   * 属性def_double的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return UFDouble
	   */
	 public UFDouble getDef_double() {
		 return def_double;
	  }   
	  
     /**
	   * 属性def_double的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newDef_double UFDouble
	   */
	public void setDef_double(UFDouble newDef_double) {
		
		def_double = newDef_double;
	 } 	  
       
        /**
	   * 属性def_str_2的Getter方法.
	   *
	   * 创建日期:2011-4-2
	   * @return String
	   */
	 public String getDef_str_2() {
		 return def_str_2;
	  }   
	  
     /**
	   * 属性def_str_2的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newDef_str_2 String
	   */
	public void setDef_str_2(String newDef_str_2) {
		
		def_str_2 = newDef_str_2;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-4-2
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_managerserver == null) {
			errFields.add(new String("pk_managerserver"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-4-2
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-4-2
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_managerserver";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-4-2
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_messservtype";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-4-2
	  */
	public DipManagerserverVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-4-2
	 * @param newPk_managerserver 主键值
	 */
	 public DipManagerserverVO(String newPk_managerserver) {
		
		// 为主键字段赋值:
		 pk_managerserver = newPk_managerserver;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-2
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_managerserver;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-2
	  * @param newPk_managerserver  String    
	  */
	 public void setPrimaryKey(String newPk_managerserver) {
				
				pk_managerserver = newPk_managerserver; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-4-2
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_messservtype"; 
				
	 }

	public MessservtypeVO getMesvo() {
		return mesvo;
	}

	public void setMesvo(MessservtypeVO mesvo) {
		this.mesvo = mesvo;
	}

	public String getThreadname() {
		return threadname;
	}

	public void setThreadname(String threadname) {
		this.threadname = threadname;
	} 
} 
