  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.authorize.browse;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-5-12
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DipADDatalookVO extends SuperVO {
           /**
	 * 
	 */
	private static final long serialVersionUID = -5305537006016066108L;
		public String datatype;
           public String pk_datalook;
           public Integer dr;
           public String ts;
           	 public Object vdef1;
             public Object vdef2;
             public Object vdef3;
             public Object vdef4;
             public Object vdef5;
             public Object vdef6;
             public Object vdef7;
             public Object vdef8;
             public Object vdef9;
             public Object vdef10;
             public Object vdef11;
             public Object vdef12;
             public Object vdef13;
             public Object vdef14;
             public Object vdef15;
             public Object vdef16;
             public Object vdef17;
             public Object vdef18;
             public Object vdef19;
             public Object vdef20;
             public Object vdef21;
             public Object vdef22;
             public Object vdef23;
             public Object vdef24;
             public Object vdef25;
             public Object vdef26;
             public Object vdef27;
             public Object vdef28;
             public Object vdef29;
             public Object vdef30;
             public Object vdef31;
             public Object vdef32;
             public Object vdef33;
             public Object vdef34;
             public Object vdef35;
             public Object vdef36;
             public Object vdef37;
             public Object vdef38;
             public Object vdef39;
             public Object vdef40;
             public Object vdef41;
             public Object vdef42;
             public Object vdef43;
             public Object vdef44;
             public Object vdef45;
             public Object vdef46;
             public Object vdef47;
             public Object vdef48;
             public Object vdef49;
             public Object vdef50;
             public Object vdef51;
             public Object vdef52;
             public Object vdef53;
             public Object vdef54;
             public Object vdef55;
             public Object vdef56;
             public Object vdef57;
             public Object vdef58;
             public Object vdef59;
             public Object vdef60;
             public Object vdef61;
             public Object vdef62;
             public Object vdef63;
             public Object vdef64;
             public Object vdef65;
             public Object vdef66;
             public Object vdef67;
             public Object vdef68;
             public Object vdef69;
             public Object vdef70;
             public Object vdef71;
             public Object vdef72;
             public Object vdef73;
             public Object vdef74;
             public Object vdef75;
             public Object vdef76;
             public Object vdef77;
             public Object vdef78;
             public Object vdef79;
             public Object vdef80;
             public Object vdef81;
             public Object vdef82;
             public Object vdef83;
             public Object vdef84;
             public Object vdef85;
             public Object vdef86;
             public Object vdef87;
             public Object vdef88;
             public Object vdef89;
             public Object vdef90;
             public Object vdef91;
             public Object vdef92;
             public Object vdef93;
             public Object vdef94;
             public Object vdef95;
             public Object vdef96;
             public Object vdef97;
             public Object vdef98;
             public Object vdef99;
             public Object vdef100;
             public String code;
             public String name;
             public String pk_datadefinit_h;
            
             public static final String  DR="dr";   
             public static final String  TS="ts";   
             public static final String  PK_DATALOOK="pk_datalook";   
             public static final String  CODE="code";
             public static final String  NAME="name";
             public static final String  PK_DATADEFINIT_H="pk_datadefinit_h";
    

       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-5-12
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_datalook == null) {
			errFields.add(new String("pk_datalook"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-5-12
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-5-12
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_datalook";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-5-12
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_datalook";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-5-12
	  */
	public DipADDatalookVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-5-12
	 * @param newPk_datalook 主键值
	 */
	 public DipADDatalookVO(String newPk_datalook) {
		
		// 为主键字段赋值:
		 pk_datalook = newPk_datalook;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-12
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_datalook;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-12
	  * @param newPk_datalook  String    
	  */
	 public void setPrimaryKey(String newPk_datalook) {
				
				pk_datalook = newPk_datalook; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-5-12
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_datalook"; 
				
	 }

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPk_datadefinit_h() {
		return pk_datadefinit_h;
	}

	public void setPk_datadefinit_h(String pk_datadefinit_h) {
		this.pk_datadefinit_h = pk_datadefinit_h;
	}

	public String getDatatype() {
		return datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}


	public Integer getDr() {
		return dr;
	}


	public void setDr(Integer dr) {
		this.dr = dr;
	}


	public String getPk_datalook() {
		return pk_datalook;
	}


	public void setPk_datalook(String pk_datalook) {
		this.pk_datalook = pk_datalook;
	}


	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	} 


	public void setTs(String ts) {
		this.ts = ts;
	}


	public Object getVdef1() {
		return vdef1;
	}


	public void setVdef1(Object vdef1) {
		this.vdef1 = vdef1;
	}


	public Object getVdef10() {
		return vdef10;
	}


	public void setVdef10(Object vdef10) {
		this.vdef10 = vdef10;
	}


	public Object getVdef100() {
		return vdef100;
	}


	public void setVdef100(Object vdef100) {
		this.vdef100 = vdef100;
	}


	public Object getVdef11() {
		return vdef11;
	}


	public void setVdef11(Object vdef11) {
		this.vdef11 = vdef11;
	}


	public Object getVdef12() {
		return vdef12;
	}


	public void setVdef12(Object vdef12) {
		this.vdef12 = vdef12;
	}


	public Object getVdef13() {
		return vdef13;
	}


	public void setVdef13(Object vdef13) {
		this.vdef13 = vdef13;
	}


	public Object getVdef14() {
		return vdef14;
	}


	public void setVdef14(Object vdef14) {
		this.vdef14 = vdef14;
	}


	public Object getVdef15() {
		return vdef15;
	}


	public void setVdef15(Object vdef15) {
		this.vdef15 = vdef15;
	}


	public Object getVdef16() {
		return vdef16;
	}


	public void setVdef16(Object vdef16) {
		this.vdef16 = vdef16;
	}


	public Object getVdef17() {
		return vdef17;
	}


	public void setVdef17(Object vdef17) {
		this.vdef17 = vdef17;
	}


	public Object getVdef18() {
		return vdef18;
	}


	public void setVdef18(Object vdef18) {
		this.vdef18 = vdef18;
	}


	public Object getVdef19() {
		return vdef19;
	}


	public void setVdef19(Object vdef19) {
		this.vdef19 = vdef19;
	}


	public Object getVdef2() {
		return vdef2;
	}


	public void setVdef2(Object vdef2) {
		this.vdef2 = vdef2;
	}


	public Object getVdef20() {
		return vdef20;
	}


	public void setVdef20(Object vdef20) {
		this.vdef20 = vdef20;
	}


	public Object getVdef21() {
		return vdef21;
	}


	public void setVdef21(Object vdef21) {
		this.vdef21 = vdef21;
	}


	public Object getVdef22() {
		return vdef22;
	}


	public void setVdef22(Object vdef22) {
		this.vdef22 = vdef22;
	}


	public Object getVdef23() {
		return vdef23;
	}


	public void setVdef23(Object vdef23) {
		this.vdef23 = vdef23;
	}


	public Object getVdef24() {
		return vdef24;
	}


	public void setVdef24(Object vdef24) {
		this.vdef24 = vdef24;
	}


	public Object getVdef25() {
		return vdef25;
	}


	public void setVdef25(Object vdef25) {
		this.vdef25 = vdef25;
	}


	public Object getVdef26() {
		return vdef26;
	}


	public void setVdef26(Object vdef26) {
		this.vdef26 = vdef26;
	}


	public Object getVdef27() {
		return vdef27;
	}


	public void setVdef27(Object vdef27) {
		this.vdef27 = vdef27;
	}


	public Object getVdef28() {
		return vdef28;
	}


	public void setVdef28(Object vdef28) {
		this.vdef28 = vdef28;
	}


	public Object getVdef29() {
		return vdef29;
	}


	public void setVdef29(Object vdef29) {
		this.vdef29 = vdef29;
	}


	public Object getVdef3() {
		return vdef3;
	}


	public void setVdef3(Object vdef3) {
		this.vdef3 = vdef3;
	}


	public Object getVdef30() {
		return vdef30;
	}


	public void setVdef30(Object vdef30) {
		this.vdef30 = vdef30;
	}


	public Object getVdef31() {
		return vdef31;
	}


	public void setVdef31(Object vdef31) {
		this.vdef31 = vdef31;
	}


	public Object getVdef32() {
		return vdef32;
	}


	public void setVdef32(Object vdef32) {
		this.vdef32 = vdef32;
	}


	public Object getVdef33() {
		return vdef33;
	}


	public void setVdef33(Object vdef33) {
		this.vdef33 = vdef33;
	}


	public Object getVdef34() {
		return vdef34;
	}


	public void setVdef34(Object vdef34) {
		this.vdef34 = vdef34;
	}


	public Object getVdef35() {
		return vdef35;
	}


	public void setVdef35(Object vdef35) {
		this.vdef35 = vdef35;
	}


	public Object getVdef36() {
		return vdef36;
	}


	public void setVdef36(Object vdef36) {
		this.vdef36 = vdef36;
	}


	public Object getVdef37() {
		return vdef37;
	}


	public void setVdef37(Object vdef37) {
		this.vdef37 = vdef37;
	}


	public Object getVdef38() {
		return vdef38;
	}


	public void setVdef38(Object vdef38) {
		this.vdef38 = vdef38;
	}


	public Object getVdef39() {
		return vdef39;
	}


	public void setVdef39(Object vdef39) {
		this.vdef39 = vdef39;
	}


	public Object getVdef4() {
		return vdef4;
	}


	public void setVdef4(Object vdef4) {
		this.vdef4 = vdef4;
	}


	public Object getVdef40() {
		return vdef40;
	}


	public void setVdef40(Object vdef40) {
		this.vdef40 = vdef40;
	}


	public Object getVdef41() {
		return vdef41;
	}


	public void setVdef41(Object vdef41) {
		this.vdef41 = vdef41;
	}


	public Object getVdef42() {
		return vdef42;
	}


	public void setVdef42(Object vdef42) {
		this.vdef42 = vdef42;
	}


	public Object getVdef43() {
		return vdef43;
	}


	public void setVdef43(Object vdef43) {
		this.vdef43 = vdef43;
	}


	public Object getVdef44() {
		return vdef44;
	}


	public void setVdef44(Object vdef44) {
		this.vdef44 = vdef44;
	}


	public Object getVdef45() {
		return vdef45;
	}


	public void setVdef45(Object vdef45) {
		this.vdef45 = vdef45;
	}


	public Object getVdef46() {
		return vdef46;
	}


	public void setVdef46(Object vdef46) {
		this.vdef46 = vdef46;
	}


	public Object getVdef47() {
		return vdef47;
	}


	public void setVdef47(Object vdef47) {
		this.vdef47 = vdef47;
	}


	public Object getVdef48() {
		return vdef48;
	}


	public void setVdef48(Object vdef48) {
		this.vdef48 = vdef48;
	}


	public Object getVdef49() {
		return vdef49;
	}


	public void setVdef49(Object vdef49) {
		this.vdef49 = vdef49;
	}


	public Object getVdef5() {
		return vdef5;
	}


	public void setVdef5(Object vdef5) {
		this.vdef5 = vdef5;
	}


	public Object getVdef50() {
		return vdef50;
	}


	public void setVdef50(Object vdef50) {
		this.vdef50 = vdef50;
	}


	public Object getVdef51() {
		return vdef51;
	}


	public void setVdef51(Object vdef51) {
		this.vdef51 = vdef51;
	}


	public Object getVdef52() {
		return vdef52;
	}


	public void setVdef52(Object vdef52) {
		this.vdef52 = vdef52;
	}


	public Object getVdef53() {
		return vdef53;
	}


	public void setVdef53(Object vdef53) {
		this.vdef53 = vdef53;
	}


	public Object getVdef54() {
		return vdef54;
	}


	public void setVdef54(Object vdef54) {
		this.vdef54 = vdef54;
	}


	public Object getVdef55() {
		return vdef55;
	}


	public void setVdef55(Object vdef55) {
		this.vdef55 = vdef55;
	}


	public Object getVdef56() {
		return vdef56;
	}


	public void setVdef56(Object vdef56) {
		this.vdef56 = vdef56;
	}


	public Object getVdef57() {
		return vdef57;
	}


	public void setVdef57(Object vdef57) {
		this.vdef57 = vdef57;
	}


	public Object getVdef58() {
		return vdef58;
	}


	public void setVdef58(Object vdef58) {
		this.vdef58 = vdef58;
	}


	public Object getVdef59() {
		return vdef59;
	}


	public void setVdef59(Object vdef59) {
		this.vdef59 = vdef59;
	}


	public Object getVdef6() {
		return vdef6;
	}


	public void setVdef6(Object vdef6) {
		this.vdef6 = vdef6;
	}


	public Object getVdef60() {
		return vdef60;
	}


	public void setVdef60(Object vdef60) {
		this.vdef60 = vdef60;
	}


	public Object getVdef61() {
		return vdef61;
	}


	public void setVdef61(Object vdef61) {
		this.vdef61 = vdef61;
	}


	public Object getVdef62() {
		return vdef62;
	}


	public void setVdef62(Object vdef62) {
		this.vdef62 = vdef62;
	}


	public Object getVdef63() {
		return vdef63;
	}


	public void setVdef63(Object vdef63) {
		this.vdef63 = vdef63;
	}


	public Object getVdef64() {
		return vdef64;
	}


	public void setVdef64(Object vdef64) {
		this.vdef64 = vdef64;
	}


	public Object getVdef65() {
		return vdef65;
	}


	public void setVdef65(Object vdef65) {
		this.vdef65 = vdef65;
	}


	public Object getVdef66() {
		return vdef66;
	}


	public void setVdef66(Object vdef66) {
		this.vdef66 = vdef66;
	}


	public Object getVdef67() {
		return vdef67;
	}


	public void setVdef67(Object vdef67) {
		this.vdef67 = vdef67;
	}


	public Object getVdef68() {
		return vdef68;
	}


	public void setVdef68(Object vdef68) {
		this.vdef68 = vdef68;
	}


	public Object getVdef69() {
		return vdef69;
	}


	public void setVdef69(Object vdef69) {
		this.vdef69 = vdef69;
	}


	public Object getVdef7() {
		return vdef7;
	}


	public void setVdef7(Object vdef7) {
		this.vdef7 = vdef7;
	}


	public Object getVdef70() {
		return vdef70;
	}


	public void setVdef70(Object vdef70) {
		this.vdef70 = vdef70;
	}


	public Object getVdef71() {
		return vdef71;
	}


	public void setVdef71(Object vdef71) {
		this.vdef71 = vdef71;
	}


	public Object getVdef72() {
		return vdef72;
	}


	public void setVdef72(Object vdef72) {
		this.vdef72 = vdef72;
	}


	public Object getVdef73() {
		return vdef73;
	}


	public void setVdef73(Object vdef73) {
		this.vdef73 = vdef73;
	}


	public Object getVdef74() {
		return vdef74;
	}


	public void setVdef74(Object vdef74) {
		this.vdef74 = vdef74;
	}


	public Object getVdef75() {
		return vdef75;
	}


	public void setVdef75(Object vdef75) {
		this.vdef75 = vdef75;
	}


	public Object getVdef76() {
		return vdef76;
	}


	public void setVdef76(Object vdef76) {
		this.vdef76 = vdef76;
	}


	public Object getVdef77() {
		return vdef77;
	}


	public void setVdef77(Object vdef77) {
		this.vdef77 = vdef77;
	}


	public Object getVdef78() {
		return vdef78;
	}


	public void setVdef78(Object vdef78) {
		this.vdef78 = vdef78;
	}


	public Object getVdef79() {
		return vdef79;
	}


	public void setVdef79(Object vdef79) {
		this.vdef79 = vdef79;
	}


	public Object getVdef8() {
		return vdef8;
	}


	public void setVdef8(Object vdef8) {
		this.vdef8 = vdef8;
	}


	public Object getVdef80() {
		return vdef80;
	}


	public void setVdef80(Object vdef80) {
		this.vdef80 = vdef80;
	}


	public Object getVdef81() {
		return vdef81;
	}


	public void setVdef81(Object vdef81) {
		this.vdef81 = vdef81;
	}


	public Object getVdef82() {
		return vdef82;
	}


	public void setVdef82(Object vdef82) {
		this.vdef82 = vdef82;
	}


	public Object getVdef83() {
		return vdef83;
	}


	public void setVdef83(Object vdef83) {
		this.vdef83 = vdef83;
	}


	public Object getVdef84() {
		return vdef84;
	}


	public void setVdef84(Object vdef84) {
		this.vdef84 = vdef84;
	}


	public Object getVdef85() {
		return vdef85;
	}


	public void setVdef85(Object vdef85) {
		this.vdef85 = vdef85;
	}


	public Object getVdef86() {
		return vdef86;
	}


	public void setVdef86(Object vdef86) {
		this.vdef86 = vdef86;
	}


	public Object getVdef87() {
		return vdef87;
	}


	public void setVdef87(Object vdef87) {
		this.vdef87 = vdef87;
	}


	public Object getVdef88() {
		return vdef88;
	}


	public void setVdef88(Object vdef88) {
		this.vdef88 = vdef88;
	}


	public Object getVdef89() {
		return vdef89;
	}


	public void setVdef89(Object vdef89) {
		this.vdef89 = vdef89;
	}


	public Object getVdef9() {
		return vdef9;
	}


	public void setVdef9(Object vdef9) {
		this.vdef9 = vdef9;
	}


	public Object getVdef90() {
		return vdef90;
	}


	public void setVdef90(Object vdef90) {
		this.vdef90 = vdef90;
	}


	public Object getVdef91() {
		return vdef91;
	}


	public void setVdef91(Object vdef91) {
		this.vdef91 = vdef91;
	}


	public Object getVdef92() {
		return vdef92;
	}


	public void setVdef92(Object vdef92) {
		this.vdef92 = vdef92;
	}


	public Object getVdef93() {
		return vdef93;
	}


	public void setVdef93(Object vdef93) {
		this.vdef93 = vdef93;
	}


	public Object getVdef94() {
		return vdef94;
	}


	public void setVdef94(Object vdef94) {
		this.vdef94 = vdef94;
	}


	public Object getVdef95() {
		return vdef95;
	}


	public void setVdef95(Object vdef95) {
		this.vdef95 = vdef95;
	}


	public Object getVdef96() {
		return vdef96;
	}


	public void setVdef96(Object vdef96) {
		this.vdef96 = vdef96;
	}


	public Object getVdef97() {
		return vdef97;
	}


	public void setVdef97(Object vdef97) {
		this.vdef97 = vdef97;
	}


	public Object getVdef98() {
		return vdef98;
	}


	public void setVdef98(Object vdef98) {
		this.vdef98 = vdef98;
	}


	public Object getVdef99() {
		return vdef99;
	}


	public void setVdef99(Object vdef99) {
		this.vdef99 = vdef99;
	} 
} 
