  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.control;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-7-20
 * @author author
 * @version Your Project 1.0
 */
     public class ControlHVO extends SuperVO {
           
             public String bustype;
             public Integer dr;
             public String ts;
             public String pk_controlh;
             public String code;
             public String name;
            
             public static final String  BUSTYPE="bustype";   
             public static final String  DR="dr";   
             public static final String  TS="ts";   
             public static final String  PK_CONTROLH="pk_controlh";   
      
    
        /**
	   * 属性bustype的Getter方法.
	   *
	   * 创建日期:2011-7-20
	   * @return String
	   */
	 public String getBustype() {
		 return bustype;
	  }   
	  
     /**
	   * 属性bustype的Setter方法.
	   *
	   * 创建日期:2011-7-20
	   * @param newBustype String
	   */
	public void setBustype(String newBustype) {
		
		bustype = newBustype;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-7-20
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-7-20
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-7-20
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-7-20
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性pk_control的Getter方法.
	   *
	   * 创建日期:2011-7-20
	   * @return String
	   */
	 public String getPk_controlh() {
		 return pk_controlh;
	  }   
	  
     /**
	   * 属性pk_control的Setter方法.
	   *h
	   * 创建日期:2011-7-20
	   * @param newPk_control String
	   */
	public void setPk_controlh(String newPk_controlh) {
		
		pk_controlh = newPk_controlh;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-7-20
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_controlh == null) {
			errFields.add(new String("pk_control"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-7-20
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-7-20
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_control";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-7-20
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_control";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-7-20
	  */
	public ControlHVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-7-20
	 * @param newPk_control 主键值
	 */
	 public ControlHVO(String newPk_controlh) {
		
		// 为主键字段赋值:
		 pk_controlh = newPk_controlh;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-7-20
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_controlh;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-7-20
	  * @param newPk_control  String    
	  */
	 public void setPrimaryKey(String newPk_controlh) {
				
				pk_controlh = newPk_controlh; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-7-20
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_control"; 
				
	 }

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	} 
} 
