  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.procondition;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-4-2
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DipProconditionVO extends SuperVO {
           

             public String pk_procondition;
             public String cname;
             public String field;
             public Integer dr;
             public String ts;
             public UFBoolean issum;
             public String code;
             public String name;
             public String firsttab;
             public UFBoolean def1;
             public String def2;
             public String def3;
             public String def4;
             public String def5;
             public UFBoolean def6;
             public String def7;
             public String def8;
             public String def9;
             public String def10;
            

             public static final String  PK_PROCONDITION="pk_procondition";   
             public static final String  DR="dr";   
             public static final String  CNAME="cname";   
             public static final String  FIELD="field";   
             public static final String  TS="ts";    
             public static final String  ISSUM="issum";    
             public static final String  CODE="code";
             public static final String  NAME="name";
             public static final String  FIRSTTAB="firsttab";
             public static final String  DEF1="def1";   
             public static final String  DEF2="def2"; 
             public static final String  DEF3="def3"; 
             public static final String  DEF4="def4"; 
             public static final String  DEF5="def5"; 
             public static final String  DEF6="def6"; 
             public static final String  DEF7="def7"; 
             public static final String  DEF8="def8"; 
             public static final String  DEF9="def9"; 
             public static final String  DEF10="def10"; 
    
        /**
	   * 属性def1的Getter方法.
	   *
	   * 创建日期:2011-4-16
	   * @return String
	   */
	 public UFBoolean getDef1() {
		 return def1;
	  }   
	  
     /**
	   * 属性def1的Setter方法.
	   *
	   * 创建日期:2011-4-16
	   * @param newDef1 String
	   */
	public void setDef1(UFBoolean newDef1) {
		
		def1 = newDef1;
	 } 	  
       
        /**
	   * 属性pk_procondition的Getter方法.
	   *
	   * 创建日期:2011-4-16
	   * @return String
	   */
	 public String getPk_procondition() {
		 return pk_procondition;
	  }   
	  
     /**
	   * 属性pk_procondition的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newPk_procondition String
	   */
	public void setPk_procondition(String newPk_procondition) {
		
		pk_procondition = newPk_procondition;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-4-16
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-4-16
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性cname的Getter方法.
	   *
	   * 创建日期:2011-4-16
	   * @return String
	   */
	 public String getCname() {
		 return cname;
	  }   
	  
     /**
	   * 属性cname的Setter方法.
	   *
	   * 创建日期:2011-4-16
	   * @param newCode String
	   */
	public void setCname(String newCname) {
		
		cname = newCname;
	 } 	  
       
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-4-16
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}  
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-4-16
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
	  
     /**
	   * 属性def_str_2的Setter方法.
	   *
	   * 创建日期:2011-4-2
	   * @param newDef_str_2 String
	   */
	public void setDef2(String newDef2) {
		
		def2 = newDef2;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-4-2
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_procondition == null) {
			errFields.add(new String("pk_procondition"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-4-2
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-4-2
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_procondition";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-4-2
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_datalook";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-4-2
	  */
	public DipProconditionVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-4-2
	 * @param newPk_processtype 主键值
	 */
	 public DipProconditionVO(String newPk_procondition) {
		
		// 为主键字段赋值:
		 pk_procondition = newPk_procondition;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-2
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_procondition;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-2
	  * @param newPk_procondition  String    
	  */
	 public void setPrimaryKey(String newPk_procondition) {
				
		 pk_procondition = newPk_procondition; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-4-2
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_datalook"; 
				
	 }

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}
    /*将def6类型及get()、set()方法的类型改为UFBoolan，在数据加工的卸载dlg选择更改时报illigle异常
     * 2011-06-21
     * zlc*/
	public UFBoolean getDef6() {
		return def6;
	}

	public void setDef6(UFBoolean def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getField() {
		return field;
	}

	public void setField(String field) {
		this.field = field;
	}

	public UFBoolean getIssum() {
		return issum;
	}

	public void setIssum(UFBoolean issum) {
		this.issum = issum;
	}

	public String getDef2() {
		return def2;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getFirsttab() {
		return firsttab;
	}

	public void setFirsttab(String firsttab) {
		this.firsttab = firsttab;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	} 
} 
