  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.tyxml;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-4-7
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DipTYXMLDatachangeBVO extends SuperVO {
           
             public String pk_tyxml_b;
             public String pk_tyxml_h;
             public String bqfield;
             public String ts;
             public String memo;
             public String pro;
             public String contrl;
             public String changformu;
             public Integer dr;
             public Integer orderno;
             public UFBoolean randstart;
             public UFBoolean randend;
             
//             public String yename;
//             public String ytype;
             
             public String fieldname;//导出字段名称
             public String fieldcode;//导出字段编码
            
             
             
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return UFDateTime
	   */
             public Object getTs() {
         		if(ts==null){
         			return null;
         		}else{
         			if(IContrastUtil.VERSION.equals("nc502")){
         				  return new UFDateTime(ts);
         			  }else if(IContrastUtil.VERSION.equals("nc507")){
         				  return ts;  
         			  }
         		}
         		return ts;
         	}    
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-4-7
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	 	if (pk_tyxml_b == null) {
			errFields.add(new String("pk_tyxml_b"));
			  }	
	   	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-4-7
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_tyxml_h";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-4-7
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_tyxml_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-4-7
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_tyxml_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-4-7
	  */
	public DipTYXMLDatachangeBVO() {
			
			   super();	
	  }    
    
           
    /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-4-2
	 * @param newPk_sysregister_b 主键值
	 */
	 public DipTYXMLDatachangeBVO(String newPk_datachange_b) {
		
		// 为主键字段赋值:
		 pk_tyxml_b = newPk_datachange_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-2
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_tyxml_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-2
	  * @param newPk_sysregister_b  String    
	  */
	 public void setPrimaryKey(String newPk_datachange_b) {
				
		 pk_tyxml_b = newPk_datachange_b; 
				
	 } 
	 
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-4-7
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_tyxml_b"; 
				
	 }

	public String getChangformu() {
		return changformu;
	}

	public void setChangformu(String changformu) {
		this.changformu = changformu;
	}

	public String getContrl() {
		return contrl;
	}

	public void setContrl(String contrl) {
		this.contrl = contrl;
	}

	public String getBqfield() {
		return bqfield;
	}

	public void setBqfield(String bqfield) {
		this.bqfield = bqfield;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getPk_tyxml_b() {
		return pk_tyxml_b;
	}

	public void setPk_tyxml_b(String pk_tyxml_b) {
		this.pk_tyxml_b = pk_tyxml_b;
	}

	public String getPk_tyxml_h() {
		return pk_tyxml_h;
	}

	public void setPk_tyxml_h(String pk_tyxml_h) {
		this.pk_tyxml_h = pk_tyxml_h;
	}

	public String getPro() {
		return pro;
	}

	public void setPro(String pro) {
		this.pro = pro;
	}

//	public String getYename() {
//		return yename;
//	}
//
//	public void setYename(String yename) {
//		this.yename = yename;
//	}
//
//	public String getYtype() {
//		return ytype;
//	}
//
//	public void setYtype(String ytype) {
//		this.ytype = ytype;
//	}

	public String getFieldcode() {
		return fieldcode;
	}

	public void setFieldcode(String fieldcode) {
		this.fieldcode = fieldcode;
	}

	public String getFieldname() {
		return fieldname;
	}

	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}

	public Integer getOrderno() {
		return orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

	public UFBoolean getRandend() {
		return randend;
	}

	public void setRandend(UFBoolean randend) {
		this.randend = randend;
	}

	public UFBoolean getRandstart() {
		return randstart;
	}

	public void setRandstart(UFBoolean randstart) {
		this.randstart = randstart;
	}

	
	
	
	
} 
