/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
package nc.vo.dip.tyzhq;

import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
import nc.vo.pub.*;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDateTime;

/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-4-7
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class DipTYZHDatachangeHVO extends SuperVO {
	public String pk_tyzhq_h;
	public String code;
	public String name;
	public String sourcetab;
	public String targettab;
	public String constatus;
	public Integer dr;
	public String endstatus;
	public String tasktype;
	public String fpk;
	public UFBoolean isfolder;
	public String pk_xt;
	public String ts;
	public String repdatactl;
	

	public String getRepdatactl() {
		return repdatactl;
	}

	public void setRepdatactl(String repdatactl) {
		this.repdatactl = repdatactl;
	}

	/**
	 * 属性tasktype的Getter方法.
	 *
	 * 创建日期:2011-4-7
	 * @return String
	 */
	public String getTasktype() {
		return tasktype;
	}   

	/**
	 * 属性tasktype的Setter方法.
	 *
	 * 创建日期:2011-4-7
	 * @param newTasktype String
	 */
	public void setTasktype(String newTasktype) {

		tasktype = newTasktype;
	} 	  

	/**
	 * 属性dr的Getter方法.
	 *
	 * 创建日期:2011-4-7
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}   

	/**
	 * 属性dr的Setter方法.
	 *
	 * 创建日期:2011-4-7
	 * @param newDr Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	} 	  


	/**
	 * 属性endstatus的Getter方法.
	 *
	 * 创建日期:2011-4-7
	 * @return String
	 */
	public String getEndstatus() {
		return endstatus;
	}   

	/**
	 * 属性endstatus的Setter方法.
	 *
	 * 创建日期:2011-4-7
	 * @param newEndstatus String
	 */
	public void setEndstatus(String newEndstatus) {

		endstatus = newEndstatus;
	} 	  

	/**
	 * 属性code的Getter方法.
	 *
	 * 创建日期:2011-4-7
	 * @return String
	 */
	public String getCode() {
		return code;
	}   

	/**
	 * 属性code的Setter方法.
	 *
	 * 创建日期:2011-4-7
	 * @param newCode String
	 */
	public void setCode(String newCode) {

		code = newCode;
	} 	  

	/**
	 * 属性ts的Getter方法.
	 *
	 * 创建日期:2011-4-7
	 * @return UFDateTime
	 */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}   

	/**
	 * 属性ts的Setter方法.
	 *
	 * 创建日期:2011-4-7
	 * @param newTs UFDateTime
	 */
	public void setTs(String newTs) {

		ts = newTs;
	} 	  


	/**
	 * 属性constatus的Getter方法.
	 *
	 * 创建日期:2011-4-7
	 * @return String
	 */
	public String getConstatus() {
		return constatus;
	}   

	/**
	 * 属性constatus的Setter方法.
	 *
	 * 创建日期:2011-4-7
	 * @param newConstatus String
	 */
	public void setConstatus(String newConstatus) {

		constatus = newConstatus;
	} 	  

	/**
	 * 属性name的Getter方法.
	 *
	 * 创建日期:2011-4-7
	 * @return String
	 */
	public String getName() {
		return name;
	}   

	/**
	 * 属性name的Setter方法.
	 *
	 * 创建日期:2011-4-7
	 * @param newName String
	 */
	public void setName(String newName) {

		name = newName;
	} 	  


	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 *
	 * 创建日期:2011-4-7
	 * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	 * ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (pk_tyzhq_h == null) {
			errFields.add(new String("pk_tyzhq_h"));
		}	

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for ( int i= 1; i < temp.length; i++ ) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}


	/**
	 * <p>取得父VO主键字段.
	 * <p>
	 * 创建日期:2011-4-7
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return "fpk";

	}   

	/**
	 * <p>取得表主键.
	 * <p>
	 * 创建日期:2011-4-7
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_tyzhq_h";
	}

	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-4-7
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "dip_tyzhq_h";
	}    

	/**
	 * 按照默认方式创建构造子.
	 *
	 * 创建日期:2011-4-7
	 */
	public DipTYZHDatachangeHVO() {

		super();	
	}    


	/**
	 * 设置对象标识,用来唯一定位对象.
	 *
	 * 创建日期:2011-4-7
	 * @param newPk_datachange_h  String    
	 */
	public void setPrimaryKey(String newPk_datachange_h) {

		pk_tyzhq_h = newPk_datachange_h; 

	} 
	   /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-2
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_tyzhq_h;
	   
	   }


	/**
	 * 返回数值对象的显示名称.
	 *
	 * 创建日期:2011-4-7
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "dip_tyzhq_h"; 

	}

	public String getFpk() {
		return fpk;
	}

	public void setFpk(String fpk) {
		this.fpk = fpk;
	}

	public UFBoolean getIsfolder() {
		return isfolder;
	}

	public void setIsfolder(UFBoolean isfolder) {
		this.isfolder = isfolder;
	}

	public String getPk_tyzhq_h() {
		return pk_tyzhq_h;
	}

	public void setPk_tyzhq_h(String pk_tyzhq_h) {
		this.pk_tyzhq_h = pk_tyzhq_h;
	}

	public String getPk_xt() {
		return pk_xt;
	}

	public void setPk_xt(String pk_xt) {
		this.pk_xt = pk_xt;
	}

	public String getSourcetab() {
		return sourcetab;
	}

	public void setSourcetab(String sourcetab) {
		this.sourcetab = sourcetab;
	}

	public String getTargettab() {
		return targettab;
	}

	public void setTargettab(String targettab) {
		this.targettab = targettab;
	}

	
} 
