  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.contdatawh;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
import nc.vo.pub.*;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDateTime;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-5-9
 * @author author
 * @version Your Project 1.0
 */
     public class ContdatawhHVO extends SuperVO {
           
             public String vdef11;
             public String vdef14;
             public String fpk;
             public String vdef4;
             public String vdef7;
             public String pk_contdatawh_h;
             public Integer dr;
             public String vdef3;
             public String vdef13;
             public String vdef9;
             public String wbbm;
             public String vdef8;
             public String vdef12;
             public String vdef2;
             public String ts;
             public String syscode;
             public String sysname;
             public String vdef6;
             public String vdef10;
             public String vdef1;
             public String vdef15;
             public String vdef5;
             
             public String vdef16;
             public String vdef17;
             public String vdef18;
             public String vdef19;
             public String vdef20;
             public String vdef21;
             public String vdef22;
             public String vdef23;
             public String vdef24;
             public String vdef25;
             public String vdef26;
             public String vdef27;
             public String vdef28;
             public String vdef29;
             public String vdef30;
             public String vdef31;
             public String vdef32;
             public String vdef33;
             public String vdef34;
             public String vdef35;
             public String vdef36;
             public String vdef37;
             public String vdef38;
             public String vdef39;
             public String vdef40;
             public String vdef41;
             public String vdef42;
             public String vdef43;
             public String vdef44;
             public String vdef45;
             public String vdef46;
             public String vdef47;
             public String vdef48;
             public String vdef49;
             public String vdef50;
             public String vdef51;
             public String vdef52;
             public String vdef53;
             public String vdef54;
             public String vdef55;
             public String vdef56;
             public String vdef57;
             public String vdef58;
             public String vdef59;
             public String vdef60;
             public String pk_xt;
             public UFBoolean isfolder; 
             
             public static final String  VDEF4="vdef4";   
             public static final String  VDEF18="vdef18";   
             public static final String  PK_CONTDATAWH_H="pk_contdatawh_h";   
             public static final String  DR="dr";   
             public static final String  VDEF42="vdef42";   
             public static final String  VDEF17="vdef17";   
             public static final String  VDEF16="vdef16";   
             public static final String  VDEF27="vdef27";   
             public static final String  VDEF12="vdef12";   
             public static final String  VDEF38="vdef38";   
             public static final String  VDEF35="vdef35";   
             public static final String  VDEF24="vdef24";   
             public static final String  TS="ts";   
             public static final String  SYSNAME="sysname";   
             public static final String  VDEF25="vdef25";   
             public static final String  VDEF60="vdef60";   
             public static final String  VDEF19="vdef19";   
             public static final String  VDEF48="vdef48";   
             public static final String  VDEF51="vdef51";   
             public static final String  VDEF3="vdef3";   
             public static final String  VDEF13="vdef13";   
             public static final String  VDEF53="vdef53";   
             public static final String  VDEF31="vdef31";   
             public static final String  VDEF50="vdef50";   
             public static final String  VDEF28="vdef28";   
             public static final String  VDEF23="vdef23";   
             public static final String  VDEF52="vdef52";   
             public static final String  VDEF44="vdef44";   
             public static final String  VDEF29="vdef29";   
             public static final String  VDEF10="vdef10";   
             public static final String  VDEF5="vdef5";   
             public static final String  VDEF33="vdef33";   
             public static final String  VDEF37="vdef37";   
             public static final String  VDEF11="vdef11";   
             public static final String  VDEF59="vdef59";   
             public static final String  VDEF7="vdef7";   
             public static final String  VDEF40="vdef40";   
             public static final String  VDEF20="vdef20";   
             public static final String  VDEF2="vdef2";   
             public static final String  VDEF56="vdef56";   
             public static final String  VDEF46="vdef46";   
             public static final String  VDEF41="vdef41";   
             public static final String  VDEF57="vdef57";   
             public static final String  VDEF34="vdef34";   
             public static final String  SYSCODE="syscode";   
             public static final String  VDEF1="vdef1";   
             public static final String  VDEF47="vdef47";   
             public static final String  VDEF26="vdef26";   
             public static final String  VDEF43="vdef43";   
             public static final String  VDEF14="vdef14";   
             public static final String  FPK="fpk";   
             public static final String  VDEF21="vdef21";   
             public static final String  VDEF32="vdef32";   
             public static final String  VDEF54="vdef54";   
             public static final String  VDEF9="vdef9";   
             public static final String  WBBM="wbbm";   
             public static final String  VDEF8="vdef8";   
             public static final String  VDEF49="vdef49";   
             public static final String  VDEF39="vdef39";   
             public static final String  VDEF45="vdef45";   
             public static final String  VDEF30="vdef30";   
             public static final String  VDEF6="vdef6";   
             public static final String  VDEF15="vdef15";   
             public static final String  VDEF36="vdef36";   
             public static final String  VDEF22="vdef22";   
             public static final String  VDEF55="vdef55";   
             public static final String  VDEF58="vdef58";   
             public static final String PK_XT="pk_xt";
             public static final String ISFOLDER="isfolder";
             
             
             public UFBoolean getIsfolder() {
 				return isfolder;
 			}

 			public void setIsfolder(UFBoolean isfolder) {
 				this.isfolder = isfolder;
 			}

 			public String getPk_xt() {
 				return pk_xt;
 			}

 			public void setPk_xt(String pk_xt) {
 				this.pk_xt = pk_xt;
 			}
    
        /**
	   * 属性vdef11的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef11() {
		 return vdef11;
	  }   
	  
     /**
	   * 属性vdef11的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef11 String
	   */
	public void setVdef11(String newVdef11) {
		
		vdef11 = newVdef11;
	 } 	  
       
        /**
	   * 属性vdef14的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef14() {
		 return vdef14;
	  }   
	  
     /**
	   * 属性vdef14的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef14 String
	   */
	public void setVdef14(String newVdef14) {
		
		vdef14 = newVdef14;
	 } 	  
       
        /**
	   * 属性fpk的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getFpk() {
		 return fpk;
	  }   
	  
     /**
	   * 属性fpk的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newFpk String
	   */
	public void setFpk(String newFpk) {
		
		fpk = newFpk;
	 } 	  
       
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性vdef7的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef7() {
		 return vdef7;
	  }   
	  
     /**
	   * 属性vdef7的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef7 String
	   */
	public void setVdef7(String newVdef7) {
		
		vdef7 = newVdef7;
	 } 	  
       
        /**
	   * 属性pk_contdatawh_h的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getPk_contdatawh_h() {
		 return pk_contdatawh_h;
	  }   
	  
     /**
	   * 属性pk_contdatawh_h的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newPk_contdatawh_h String
	   */
	public void setPk_contdatawh_h(String newPk_contdatawh_h) {
		
		pk_contdatawh_h = newPk_contdatawh_h;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性vdef13的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef13() {
		 return vdef13;
	  }   
	  
     /**
	   * 属性vdef13的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef13 String
	   */
	public void setVdef13(String newVdef13) {
		
		vdef13 = newVdef13;
	 } 	  
       
        /**
	   * 属性vdef9的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef9() {
		 return vdef9;
	  }   
	  
     /**
	   * 属性vdef9的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef9 String
	   */
	public void setVdef9(String newVdef9) {
		
		vdef9 = newVdef9;
	 } 	  
       
        /**
	   * 属性wbbm的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getWbbm() {
		 return wbbm;
	  }   
	  
     /**
	   * 属性wbbm的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newWbbm String
	   */
	public void setWbbm(String newWbbm) {
		
		wbbm = newWbbm;
	 } 	  
       
        /**
	   * 属性vdef8的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef8() {
		 return vdef8;
	  }   
	  
     /**
	   * 属性vdef8的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef8 String
	   */
	public void setVdef8(String newVdef8) {
		
		vdef8 = newVdef8;
	 } 	  
       
        /**
	   * 属性vdef12的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef12() {
		 return vdef12;
	  }   
	  
     /**
	   * 属性vdef12的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef12 String
	   */
	public void setVdef12(String newVdef12) {
		
		vdef12 = newVdef12;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	} 
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性syscode的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getSyscode() {
		 return syscode;
	  }   
	  
     /**
	   * 属性syscode的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newSyscode String
	   */
	public void setSyscode(String newSyscode) {
		
		syscode = newSyscode;
	 } 	  
       
        /**
	   * 属性sysname的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getSysname() {
		 return sysname;
	  }   
	  
     /**
	   * 属性sysname的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newSysname String
	   */
	public void setSysname(String newSysname) {
		
		sysname = newSysname;
	 } 	  
       
        /**
	   * 属性vdef6的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef6() {
		 return vdef6;
	  }   
	  
     /**
	   * 属性vdef6的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef6 String
	   */
	public void setVdef6(String newVdef6) {
		
		vdef6 = newVdef6;
	 } 	  
       
        /**
	   * 属性vdef10的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef10() {
		 return vdef10;
	  }   
	  
     /**
	   * 属性vdef10的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef10 String
	   */
	public void setVdef10(String newVdef10) {
		
		vdef10 = newVdef10;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性vdef15的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef15() {
		 return vdef15;
	  }   
	  
     /**
	   * 属性vdef15的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef15 String
	   */
	public void setVdef15(String newVdef15) {
		
		vdef15 = newVdef15;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2011-5-9
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2011-5-9
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-5-9
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_contdatawh_h == null) {
			errFields.add(new String("pk_contdatawh_h"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-5-9
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-5-9
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_contdatawh_h";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-5-9
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_contdatawh_h";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-5-9
	  */
	public ContdatawhHVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-5-9
	 * @param newPk_contdatawh_h 主键值
	 */
	 public ContdatawhHVO(String newPk_contdatawh_h) {
		
		// 为主键字段赋值:
		 pk_contdatawh_h = newPk_contdatawh_h;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-9
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_contdatawh_h;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-9
	  * @param newPk_contdatawh_h  String    
	  */
	 public void setPrimaryKey(String newPk_contdatawh_h) {
				
				pk_contdatawh_h = newPk_contdatawh_h; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-5-9
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_contdatawh_h"; 
				
	 }

	public String getVdef16() {
		return vdef16;
	}

	public void setVdef16(String vdef16) {
		this.vdef16 = vdef16;
	}

	public String getVdef17() {
		return vdef17;
	}

	public void setVdef17(String vdef17) {
		this.vdef17 = vdef17;
	}

	public String getVdef18() {
		return vdef18;
	}

	public void setVdef18(String vdef18) {
		this.vdef18 = vdef18;
	}

	public String getVdef19() {
		return vdef19;
	}

	public void setVdef19(String vdef19) {
		this.vdef19 = vdef19;
	}

	public String getVdef20() {
		return vdef20;
	}

	public void setVdef20(String vdef20) {
		this.vdef20 = vdef20;
	}

	public String getVdef21() {
		return vdef21;
	}

	public void setVdef21(String vdef21) {
		this.vdef21 = vdef21;
	}

	public String getVdef22() {
		return vdef22;
	}

	public void setVdef22(String vdef22) {
		this.vdef22 = vdef22;
	}

	public String getVdef23() {
		return vdef23;
	}

	public void setVdef23(String vdef23) {
		this.vdef23 = vdef23;
	}

	public String getVdef24() {
		return vdef24;
	}

	public void setVdef24(String vdef24) {
		this.vdef24 = vdef24;
	}

	public String getVdef25() {
		return vdef25;
	}

	public void setVdef25(String vdef25) {
		this.vdef25 = vdef25;
	}

	public String getVdef26() {
		return vdef26;
	}

	public void setVdef26(String vdef26) {
		this.vdef26 = vdef26;
	}

	public String getVdef27() {
		return vdef27;
	}

	public void setVdef27(String vdef27) {
		this.vdef27 = vdef27;
	}

	public String getVdef28() {
		return vdef28;
	}

	public void setVdef28(String vdef28) {
		this.vdef28 = vdef28;
	}

	public String getVdef29() {
		return vdef29;
	}

	public void setVdef29(String vdef29) {
		this.vdef29 = vdef29;
	}

	public String getVdef30() {
		return vdef30;
	}

	public void setVdef30(String vdef30) {
		this.vdef30 = vdef30;
	}

	public String getVdef31() {
		return vdef31;
	}

	public void setVdef31(String vdef31) {
		this.vdef31 = vdef31;
	}

	public String getVdef32() {
		return vdef32;
	}

	public void setVdef32(String vdef32) {
		this.vdef32 = vdef32;
	}

	public String getVdef33() {
		return vdef33;
	}

	public void setVdef33(String vdef33) {
		this.vdef33 = vdef33;
	}

	public String getVdef34() {
		return vdef34;
	}

	public void setVdef34(String vdef34) {
		this.vdef34 = vdef34;
	}

	public String getVdef35() {
		return vdef35;
	}

	public void setVdef35(String vdef35) {
		this.vdef35 = vdef35;
	}

	public String getVdef36() {
		return vdef36;
	}

	public void setVdef36(String vdef36) {
		this.vdef36 = vdef36;
	}

	public String getVdef37() {
		return vdef37;
	}

	public void setVdef37(String vdef37) {
		this.vdef37 = vdef37;
	}

	public String getVdef38() {
		return vdef38;
	}

	public void setVdef38(String vdef38) {
		this.vdef38 = vdef38;
	}

	public String getVdef39() {
		return vdef39;
	}

	public void setVdef39(String vdef39) {
		this.vdef39 = vdef39;
	}

	public String getVdef40() {
		return vdef40;
	}

	public void setVdef40(String vdef40) {
		this.vdef40 = vdef40;
	}

	public String getVdef41() {
		return vdef41;
	}

	public void setVdef41(String vdef41) {
		this.vdef41 = vdef41;
	}

	public String getVdef42() {
		return vdef42;
	}

	public void setVdef42(String vdef42) {
		this.vdef42 = vdef42;
	}

	public String getVdef43() {
		return vdef43;
	}

	public void setVdef43(String vdef43) {
		this.vdef43 = vdef43;
	}

	public String getVdef44() {
		return vdef44;
	}

	public void setVdef44(String vdef44) {
		this.vdef44 = vdef44;
	}

	public String getVdef45() {
		return vdef45;
	}

	public void setVdef45(String vdef45) {
		this.vdef45 = vdef45;
	}

	public String getVdef46() {
		return vdef46;
	}

	public void setVdef46(String vdef46) {
		this.vdef46 = vdef46;
	}

	public String getVdef47() {
		return vdef47;
	}

	public void setVdef47(String vdef47) {
		this.vdef47 = vdef47;
	}

	public String getVdef48() {
		return vdef48;
	}

	public void setVdef48(String vdef48) {
		this.vdef48 = vdef48;
	}

	public String getVdef49() {
		return vdef49;
	}

	public void setVdef49(String vdef49) {
		this.vdef49 = vdef49;
	}

	public String getVdef50() {
		return vdef50;
	}

	public void setVdef50(String vdef50) {
		this.vdef50 = vdef50;
	}

	public String getVdef51() {
		return vdef51;
	}

	public void setVdef51(String vdef51) {
		this.vdef51 = vdef51;
	}

	public String getVdef52() {
		return vdef52;
	}

	public void setVdef52(String vdef52) {
		this.vdef52 = vdef52;
	}

	public String getVdef53() {
		return vdef53;
	}

	public void setVdef53(String vdef53) {
		this.vdef53 = vdef53;
	}

	public String getVdef54() {
		return vdef54;
	}

	public void setVdef54(String vdef54) {
		this.vdef54 = vdef54;
	}

	public String getVdef55() {
		return vdef55;
	}

	public void setVdef55(String vdef55) {
		this.vdef55 = vdef55;
	}

	public String getVdef56() {
		return vdef56;
	}

	public void setVdef56(String vdef56) {
		this.vdef56 = vdef56;
	}

	public String getVdef57() {
		return vdef57;
	}

	public void setVdef57(String vdef57) {
		this.vdef57 = vdef57;
	}

	public String getVdef58() {
		return vdef58;
	}

	public void setVdef58(String vdef58) {
		this.vdef58 = vdef58;
	}

	public String getVdef59() {
		return vdef59;
	}

	public void setVdef59(String vdef59) {
		this.vdef59 = vdef59;
	}

	public String getVdef60() {
		return vdef60;
	}

	public void setVdef60(String vdef60) {
		this.vdef60 = vdef60;
	} 
} 
