  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.datachange;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-4-7
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class DipDatachangeBVO extends SuperVO {
           
             public String orgname;
             public String def_str_1;
             public String ts;
             public UFBoolean issystmp;
             public String pk_datachange_h;
             public String pk_datachange_b;
             public String orgcode;
             public String tempexist;
             public UFBoolean disable;
             public Integer dr;
             public String def_str_2;
             public UFBoolean isselect;
            
             public static final String  ORGNAME="orgname";   
             public static final String  DEF_STR_1="def_str_1";   
             public static final String  TS="ts";   
             public static final String  ISSYSTMP="issystmp";   
             public static final String  PK_DATACHANGE_H="pk_datachange_h";   
             public static final String  PK_DATACHANGE_B="pk_datachange_b";   
             public static final String  ORGCODE="orgcode";   
             public static final String  TEMPEXIST="tempexist";   
             public static final String  DISABLE="disable";   
             public static final String  DR="dr";   
             public static final String  DEF_STR_2="def_str_2";   
             public static final String  ISSELECT="isselect";   
      
    
        /**
	   * 属性orgname的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return String
	   */
	 public String getOrgname() {
		 return orgname;
	  }   
	  
     /**
	   * 属性orgname的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newOrgname String
	   */
	public void setOrgname(String newOrgname) {
		
		orgname = newOrgname;
	 } 	  
       
        /**
	   * 属性def_str_1的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return String
	   */
	 public String getDef_str_1() {
		 return def_str_1;
	  }   
	  
     /**
	   * 属性def_str_1的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newDef_str_1 String
	   */
	public void setDef_str_1(String newDef_str_1) {
		
		def_str_1 = newDef_str_1;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return UFDateTime
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newTs UFDateTime
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性issystmp的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return UFBoolean
	   */
	 public UFBoolean getIssystmp() {
		 return issystmp;
	  }   
	  
     /**
	   * 属性issystmp的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newIssystmp UFBoolean
	   */
	public void setIssystmp(UFBoolean newIssystmp) {
		
		issystmp = newIssystmp;
	 } 	  
       
        /**
	   * 属性pk_datachange_h的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return String
	   */
	 public String getPk_datachange_h() {
		 return pk_datachange_h;
	  }   
	  
     /**
	   * 属性pk_datachange_h的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newPk_datachange_h String
	   */
	public void setPk_datachange_h(String newPk_datachange_h) {
		
		pk_datachange_h = newPk_datachange_h;
	 } 	  
       
        /**
	   * 属性pk_datachange_b的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return String
	   */
	 public String getPk_datachange_b() {
		 return pk_datachange_b;
	  }   
	  
     /**
	   * 属性pk_datachange_b的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newPk_datachange_b String
	   */
	public void setPk_datachange_b(String newPk_datachange_b) {
		
		pk_datachange_b = newPk_datachange_b;
	 } 	  
       
        /**
	   * 属性orgcode的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return String
	   */
	 public String getOrgcode() {
		 return orgcode;
	  }   
	  
     /**
	   * 属性orgcode的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newOrgcode String
	   */
	public void setOrgcode(String newOrgcode) {
		
		orgcode = newOrgcode;
	 } 	  
       
        /**
	   * 属性tempexist的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return String
	   */
	 public String getTempexist() {
		 return tempexist;
	  }   
	  
     /**
	   * 属性tempexist的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newTempexist String
	   */
	public void setTempexist(String newTempexist) {
		
		tempexist = newTempexist;
	 } 	  
       
        /**
	   * 属性disable的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return UFBoolean
	   */
	 public UFBoolean getDisable() {
		 return disable;
	  }   
	  
     /**
	   * 属性disable的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newDisable UFBoolean
	   */
	public void setDisable(UFBoolean newDisable) {
		
		disable = newDisable;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性def_str_2的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return String
	   */
	 public String getDef_str_2() {
		 return def_str_2;
	  }   
	  
     /**
	   * 属性def_str_2的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newDef_str_2 String
	   */
	public void setDef_str_2(String newDef_str_2) {
		
		def_str_2 = newDef_str_2;
	 } 	  
       
        /**
	   * 属性isselect的Getter方法.
	   *
	   * 创建日期:2011-4-7
	   * @return UFBoolean
	   */
	 public UFBoolean getIsselect() {
		 return isselect;
	  }   
	  
     /**
	   * 属性isselect的Setter方法.
	   *
	   * 创建日期:2011-4-7
	   * @param newIsselect UFBoolean
	   */
	public void setIsselect(UFBoolean newIsselect) {
		
		isselect = newIsselect;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-4-7
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	 	if (pk_datachange_b == null) {
			errFields.add(new String("pk_datachange_b"));
			  }	
	   	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-4-7
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_datachange_h";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-4-7
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_datachange_b";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-4-7
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_datachange_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-4-7
	  */
	public DipDatachangeBVO() {
			
			   super();	
	  }    
    
           
    /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-4-2
	 * @param newPk_sysregister_b 主键值
	 */
	 public DipDatachangeBVO(String newPk_datachange_b) {
		
		// 为主键字段赋值:
		 pk_datachange_b = newPk_datachange_b;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-2
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_datachange_b;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-2
	  * @param newPk_sysregister_b  String    
	  */
	 public void setPrimaryKey(String newPk_datachange_b) {
				
		 pk_datachange_b = newPk_datachange_b; 
				
	 } 
	 
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-4-7
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_datachange_b"; 
				
	 } 
} 
