  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.dip.dbcontype;
   	
	import java.util.ArrayList;

import nc.util.dip.sj.IContrastUtil;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-6-3
 * @author author
 * @version Your Project 1.0
 */
     public class DbcontypeVO extends SuperVO {
           
             public String password;
             public String vdef4;
             public String type;
             public String constr;
             public Integer dr;
             public String vdef3;
             public String code;
             public String vdef2;
             public String pk_dbcontype;
             public String usercode;
             public String ts;
             public String vdef1;
             public String vdef5;
             public String name;
            
             public static final String  PASSWORD="password";   
             public static final String  VDEF4="vdef4";   
             public static final String  TYPE="type";   
             public static final String  CONSTR="constr";   
             public static final String  DR="dr";   
             public static final String  VDEF3="vdef3";   
             public static final String  CODE="code";   
             public static final String  VDEF2="vdef2";   
             public static final String  PK_DBCONTYPE="pk_dbcontype";   
             public static final String  USERCODE="usercode";   
             public static final String  TS="ts";   
             public static final String  VDEF1="vdef1";   
             public static final String  VDEF5="vdef5";   
             public static final String  NAME="name";   
      
    
        /**
	   * 属性password的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getPassword() {
		 return password;
	  }   
	  
     /**
	   * 属性password的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newPassword String
	   */
	public void setPassword(String newPassword) {
		
		password = newPassword;
	 } 	  
       
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性type的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getType() {
		 return type;
	  }   
	  
     /**
	   * 属性type的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newType String
	   */
	public void setType(String newType) {
		
		type = newType;
	 } 	  
       
        /**
	   * 属性constr的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getConstr() {
		 return constr;
	  }   
	  
     /**
	   * 属性constr的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newConstr String
	   */
	public void setConstr(String newConstr) {
		
		constr = newConstr;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性code的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getCode() {
		 return code;
	  }   
	  
     /**
	   * 属性code的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newCode String
	   */
	public void setCode(String newCode) {
		
		code = newCode;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性pk_dbcontype的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getPk_dbcontype() {
		 return pk_dbcontype;
	  }   
	  
     /**
	   * 属性pk_dbcontype的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newPk_dbcontype String
	   */
	public void setPk_dbcontype(String newPk_dbcontype) {
		
		pk_dbcontype = newPk_dbcontype;
	 } 	  
       
        /**
	   * 属性usercode的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getUsercode() {
		 return usercode;
	  }   
	  
     /**
	   * 属性usercode的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newUsercode String
	   */
	public void setUsercode(String newUsercode) {
		
		usercode = newUsercode;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return UFDate
	   */
	public Object getTs() {
		if(ts==null){
			return null;
		}else{
			if(IContrastUtil.VERSION.equals("nc502")){
				  return new UFDateTime(ts);
			  }else if(IContrastUtil.VERSION.equals("nc507")){
				  return ts;  
			  }
		}
		return ts;
	}   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newTs UFDate
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
        /**
	   * 属性name的Getter方法.
	   *
	   * 创建日期:2011-6-3
	   * @return String
	   */
	 public String getName() {
		 return name;
	  }   
	  
     /**
	   * 属性name的Setter方法.
	   *
	   * 创建日期:2011-6-3
	   * @param newName String
	   */
	public void setName(String newName) {
		
		name = newName;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-6-3
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_dbcontype == null) {
			errFields.add(new String("pk_dbcontype"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-6-3
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-6-3
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_dbcontype";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-6-3
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "dip_dbcontype";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-6-3
	  */
	public DbcontypeVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-6-3
	 * @param newPk_dbcontype 主键值
	 */
	 public DbcontypeVO(String newPk_dbcontype) {
		
		// 为主键字段赋值:
		 pk_dbcontype = newPk_dbcontype;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-6-3
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_dbcontype;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-6-3
	  * @param newPk_dbcontype  String    
	  */
	 public void setPrimaryKey(String newPk_dbcontype) {
				
				pk_dbcontype = newPk_dbcontype; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-6-3
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "dip_dbcontype"; 
				
	 } 
} 
